// AL-ANQA — offensive security firmware for LilyGo T-DECK
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Abdallah Natsheh
//
// Notes cover UI — Phase 2. Visual spec + palette from the approved mockup
// (trex-undercover-notes.html); mockup is drawn 2x, real px = mockup / 2.
// Draws directly to the global LGFX (like buddy/editor). Text uses anti-aliased
// Noto Sans (Android's font family) baked to VLW smooth fonts — notes_fonts.h,
// generated by convert_font.py — for a modern, non-terminal look.
//
// Notes are REAL: /apps/notes/*.txt on SD (see SD_DIR_NOTES). Line 1 = title,
// remaining lines = body (plain text, no
// checklist support — this is a keyboard-typable notes app, not a demo).
// No SD → falls back to an in-RAM starter set; edits don't persist (session-only,
// same "No SD" degrade pattern used everywhere else in this firmware).

#include "notes_ui.h"
#include "undercover_config.h"
#include "display_manager.h"
#include "input_handling.h"
#include "touch_manager.h"
#include "lockscreen_manager.h"
#include "powersave_manager.h"
#include "sdcard_manager.h"
#include "cover_statusbar.h"  // shared phone status bar (also used by home_ui)
#include "cover_kit.h"        // shared cover shell: sprite, fonts, passphrase, touch-wake
#include <Arduino.h>
#include <SD.h>
#include <vector>
#include <algorithm>

extern LGFX           tft;
extern DisplayManager displayManager;
extern InputHandling  inputHandler;
extern SDCardManager  sdCardManager;

// ── Draw context — shared cover shell (sprite/fonts owned by cover_kit) ──────
// All draws go through `G` (a full-screen PSRAM sprite composed off-screen then
// blitted in one pushSprite — no flicker). The sprite, the baked Noto VLW fonts,
// the passphrase buffer and the touch-wake now live in cover_kit (shared with the
// home launcher). Aliases keep the existing `G->...` / `&s_fBig` call sites intact.
static lgfx::LovyanGFX*& G       = cover::G;
static lgfx::VLWfont&    s_fBig   = cover::fBig;
static lgfx::VLWfont&    s_fTitle = cover::fTitle;
static lgfx::VLWfont&    s_fBody  = cover::fBody;
static lgfx::VLWfont&    s_fMeta  = cover::fMeta;

// ── Palette (RGB565, set once in runNotesUi from the mockup hex) ─────────────
static uint16_t C_PAPER, C_CARD, C_INK, C_MUTED, C_HAIR, C_ACCENT;
static uint16_t C_SEARCH, C_PREV, C_META, C_SHADOW, C_SAVED;

static void initColors() {
    C_PAPER  = G->color565(0xF7, 0xF5, 0xF0);
    C_CARD   = G->color565(0xFF, 0xFF, 0xFF);
    C_INK    = G->color565(0x23, 0x21, 0x1C);
    C_MUTED  = G->color565(0x9A, 0x96, 0x8C);
    C_HAIR   = G->color565(0xEC, 0xE9, 0xE2);
    C_ACCENT = G->color565(0xF4, 0xB7, 0x40);
    C_SEARCH = G->color565(0xEF, 0xEB, 0xE3);
    C_PREV   = G->color565(0x8A, 0x86, 0x7C);
    C_META   = G->color565(0xB4, 0xB0, 0xA6);
    C_SHADOW = G->color565(0xE4, 0xE0, 0xD7);   // soft drop shadow on paper
    C_SAVED  = G->color565(0x4C, 0xAF, 0x50);   // save-confirmation green
}

// ── Real notes (SD-backed) ────────────────────────────────────────────────────
// One file per note: /apps/notes/NNN.txt — line 1 = title, remaining lines = body.
// No SD → falls back to an in-RAM starter set (session-only, not persisted).
struct NoteRec {
    String              title;
    std::vector<String> body;    // always >=1 element while a note is open
    String              path;    // "/apps/notes/NNN.txt"; empty = never saved yet
    bool                dirty = false;
};
static std::vector<NoteRec> s_notes;   // loaded on entry, freed on exit (rule 5c)

// ── Functional search state ──────────────────────────────────────────────────
// s_query = the live search text; s_filtered = indices into s_notes that match it
// (all notes when the query is empty). The list view iterates s_filtered, not
// s_notes, so filtering is "just" choosing which indices to show — same as a
// regular phone notes app. s_searchFocused = the pill is the trackball highlight;
// s_searchActive = keystrokes are being typed into the query.
static String           s_query;
static std::vector<int> s_filtered;
static bool             s_searchActive  = false;
static bool             s_searchFocused = false;
static bool             s_backFocused   = false;   // back-to-Home chevron highlighted (only when s_fromHome)
static bool             s_fabFocused    = false;   // + FAB highlighted (encoder focus; T-Pager-critical)

static bool parseIndex(const String& fname, int& idxOut) {
    int dot = fname.lastIndexOf('.');
    if (dot <= 0) return false;
    String num = fname.substring(0, dot);
    for (size_t i = 0; i < num.length(); i++) if (!isDigit(num[i])) return false;
    idxOut = num.toInt();
    return true;
}

static bool loadNoteFile(const String& path, NoteRec& out) {
    File f = SD.open(path.c_str(), FILE_READ);
    if (!f) return false;
    out.path = path;
    out.dirty = false;
    bool first = true;
    while (f.available()) {
        String line = f.readStringUntil('\n');
        if (line.endsWith("\r")) line.remove(line.length() - 1);
        if (first) { out.title = line; first = false; }
        else        out.body.push_back(line);
    }
    f.close();
    if (out.body.empty()) out.body.push_back("");
    if (out.title.length() == 0) out.title = "Untitled";
    return true;
}

// Assigns the next free sequential filename if unsaved, writes title+body.
static bool saveNote(NoteRec& n) {
    if (!sdCardManager.canAccessSD()) return false;
    if (n.title.length() == 0) n.title = "Untitled";
    if (n.path.length() == 0) {
        sdCardManager.ensureDir(SD_DIR_NOTES);
        char path[32];
        int idx = 1;
        do { snprintf(path, sizeof(path), "%s/%03d.txt", SD_DIR_NOTES, idx++); } while (SD.exists(path));
        n.path = path;
    }
    File f = SD.open(n.path.c_str(), FILE_WRITE);
    if (!f) return false;
    f.println(n.title);
    for (auto& line : n.body) f.println(line);
    f.close();
    n.dirty = false;
    return true;
}

struct NoteSeed { const char* title; std::initializer_list<const char*> lines; };
static const NoteSeed kSeeds[] = {
    {"Lemon cake",   {"Preheat oven to 180C.", "Cream 200g butter with 200g sugar.",
                       "Add 3 eggs, one at a time.", "Fold in 200g flour + zest of 2 lemons.",
                       "Bake 35-40 min."}},
    {"Weekend trip", {"Charger + cable", "Passport", "Sunscreen", "The blue book", "Swim stuff"}},
    {"Groceries",    {"Milk", "Eggs", "Coffee beans", "Bananas", "Olive oil", "Sourdough loaf"}},
    {"Home WiFi",    {"Network: Skyfall_5G", "Password is on the fridge magnet by the door.",
                       "Guest network: Skyfall_guest"}},
};

// Writes the starter set as REAL files — used on first run so a PC-browsed
// card looks lived-in immediately (plan: "ship 4-6 believable decoy notes").
static void seedStarterFiles() {
    for (auto& s : kSeeds) {
        NoteRec n; n.title = s.title;
        for (auto* l : s.lines) n.body.push_back(l);
        saveNote(n);
    }
}

static void scanNotesDir(std::vector<std::pair<int, String>>& entries) {
    entries.clear();
    File dir = SD.open(SD_DIR_NOTES);
    if (!dir || !dir.isDirectory()) { if (dir) dir.close(); return; }
    File f = dir.openNextFile();
    while (f) {
        if (!f.isDirectory()) {
            String base(f.name());
            if (base.endsWith(".txt")) {
                int idx;
                if (parseIndex(base, idx))
                    entries.push_back({idx, String(SD_DIR_NOTES) + "/" + base});
            }
        }
        f = dir.openNextFile();
    }
    dir.close();
}

static void loadNotesFromSD() {
    s_notes.clear();

    if (!sdCardManager.canAccessSD()) {
        // No SD — small in-RAM starter set; edits are session-only (not saved).
        for (auto& s : kSeeds) {
            NoteRec n; n.title = s.title;
            for (auto* l : s.lines) n.body.push_back(l);
            s_notes.push_back(n);
        }
        return;
    }

    sdCardManager.ensureDir(SD_DIR_NOTES);
    std::vector<std::pair<int, String>> entries;
    scanNotesDir(entries);
    if (entries.empty()) {
        seedStarterFiles();
        scanNotesDir(entries);
    }

    // newest-first
    std::sort(entries.begin(), entries.end(),
              [](const std::pair<int, String>& a, const std::pair<int, String>& b) { return a.first > b.first; });

    for (auto& e : entries) {
        NoteRec n;
        if (loadNoteFile(e.second, n)) s_notes.push_back(n);
    }
}

static String notePreview(const NoteRec& n) {
    for (auto& line : n.body) { String t = line; t.trim(); if (t.length()) return t; }
    return String("(empty)");
}

// Case-insensitive substring match on title OR any body line. `ql` is expected
// already-lowercased by the caller (rebuildFilter) so we don't re-lower per note.
static bool noteMatches(const NoteRec& n, const String& ql) {
    if (ql.length() == 0) return true;
    String t = n.title; t.toLowerCase();
    if (t.indexOf(ql) >= 0) return true;
    for (auto& line : n.body) { String l = line; l.toLowerCase(); if (l.indexOf(ql) >= 0) return true; }
    return false;
}

// Rebuild s_filtered from s_query. Call after any query or notes-set change.
static void rebuildFilter() {
    String ql = s_query; ql.toLowerCase();
    s_filtered.clear();
    for (int i = 0; i < (int)s_notes.size(); i++)
        if (noteMatches(s_notes[i], ql)) s_filtered.push_back(i);
}

// ── Layout (from board cover profile in metrics.h) ───────────────────────────
#define SB_H        COVER_SB_H
#if COVER_NOTES_TWO_PANE
#define PANE_L_W    COVER_NOTES_LIST_W
#define PANE_R_X    COVER_NOTES_LIST_W
#define PANE_R_W    (SCREEN_WIDTH - PANE_L_W)
#define APPBAR_Y    COVER_NOTES_APPBAR_Y
#define SEARCH_Y    COVER_NOTES_SEARCH_Y
#define SEARCH_H    COVER_NOTES_SEARCH_H
#define LIST_TOP    (SEARCH_Y + SEARCH_H + 4)
#define CARD_X      6
#define CARD_W      (PANE_L_W - 12)
#define CARD_H      COVER_NOTES_CARD_H
#define CARD_GAP    4
#define LABEL_H     16
#define FAB_R       COVER_NOTES_FAB_R
#define FAB_CX      (PANE_L_W - 12 - FAB_R)
#define FAB_CY      (SCREEN_HEIGHT - 12 - FAB_R)
#define DOC_TOP     COVER_NOTES_DOC_TOP
#define DOC_X       (PANE_R_X + 12)
#define DOC_MAX_W   (PANE_R_W - 28)
#define LIST_W      PANE_L_W
#else
#define APPBAR_Y    COVER_NOTES_APPBAR_Y
#define SEARCH_Y    COVER_NOTES_SEARCH_Y
#define SEARCH_H    COVER_NOTES_SEARCH_H
#define LIST_TOP    (SEARCH_Y + SEARCH_H + 8)
#define CARD_X      10
#define CARD_W      (SCREEN_WIDTH - 20)
#define CARD_H      COVER_NOTES_CARD_H
#define CARD_GAP    6
#define LABEL_H     18
#define FAB_R       COVER_NOTES_FAB_R
#define FAB_CX      (SCREEN_WIDTH - 14 - FAB_R)
#define FAB_CY      (SCREEN_HEIGHT - 14 - FAB_R)
#define DOC_TOP     COVER_NOTES_DOC_TOP
#define DOC_X       26
#define DOC_MAX_W   (SCREEN_WIDTH - 46)
#define LIST_W      SCREEN_WIDTH
#endif

enum { VIEW_LIST, VIEW_DETAIL };

// true when the Notes UI was launched from the Home launcher (standalone=false):
// draws a back-to-Home chevron in the list appbar and makes [q]/the chevron return
// to Home instead of the CLI. Set at the top of runNotesUi().
static bool s_fromHome = false;

// unscrolled top offset (from LIST_TOP) of card i, and total content height —
// flat single-section list (no pinned/tint — that was demo-only decoration).
static int cardTop(int i) { return LABEL_H + i * (CARD_H + CARD_GAP); }
static int contentHeight() {
    int n = (int)s_filtered.size();
    return n > 0 ? cardTop(n - 1) + CARD_H + CARD_GAP : LABEL_H;
}
static int maxScroll() {
    int h = contentHeight() - (SCREEN_HEIGHT - LIST_TOP);
    return h > 0 ? h : 0;
}

// truncate a string with ".." so it fits maxW at the current font
static void drawClipped(const char* s, int x, int y, int maxW, uint16_t color) {
    G->setTextColor(color);
    if (G->textWidth(s) <= maxW) { G->drawString(s, x, y); return; }
    String str(s);
    while (str.length() && G->textWidth((str + "..").c_str()) > maxW) str.remove(str.length() - 1);
    G->drawString((str + "..").c_str(), x, y);
}

// ── Status chrome — the SHARED phone status bar (identical to the home cover) ──
// Real clock, carrier, signal, and battery + charging bolt; live via ClockManager
// / BatteryManager. Same bar the home launcher draws (cover_statusbar.cpp).
static void drawStatusBar() {
    drawCoverStatusBar(G, &s_fMeta);
}

// ── LIST view ────────────────────────────────────────────────────────────────
static void drawCard(int i, int screenY, bool selected) {
    const NoteRec& n = s_notes[i];
    G->fillSmoothRoundRect(CARD_X + 1, screenY + 2, CARD_W, CARD_H, 11, C_SHADOW);
    G->fillSmoothRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, C_CARD);
    if (selected) {
        G->drawRoundRect(CARD_X - 2, screenY - 2, CARD_W + 4, CARD_H + 4, 12, C_ACCENT);
        G->drawRoundRect(CARD_X - 1, screenY - 1, CARD_W + 2, CARD_H + 2, 11, C_ACCENT);
    } else {
        G->drawRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, C_HAIR);
    }

    int tx = CARD_X + 10;
#if COVER_NOTES_TWO_PANE
    G->setFont(&s_fTitle);
    drawClipped(n.title.c_str(), tx, screenY + 6, CARD_X + CARD_W - 10 - tx, C_INK);
    G->setFont(&s_fMeta);
    drawClipped(notePreview(n).c_str(), tx, screenY + 24, CARD_W - 20, C_PREV);
#else
    G->setFont(&s_fTitle);
    drawClipped(n.title.c_str(), tx, screenY + 9, CARD_X + CARD_W - 13 - tx, C_INK);
    G->setFont(&s_fMeta);
    drawClipped(notePreview(n).c_str(), tx, screenY + 31, CARD_W - 26, C_PREV);
    G->setTextColor(C_META);
    int lc = (int)n.body.size();
    char m[24]; snprintf(m, sizeof(m), "%d line%s", lc, lc == 1 ? "" : "s");
    G->drawString(m, tx, screenY + 43);
#endif
}

static void drawSectionLabel(const char* s, int screenY) {
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    G->drawString(s, CARD_X + 4, screenY + 2);
}

static void drawList(int scroll, int sel, bool caretOn) {
    G->fillRect(0, SB_H, LIST_W, SCREEN_HEIGHT - SB_H, C_PAPER);
#if COVER_NOTES_TWO_PANE
    // Keep the right pane from flashing through while we only redraw the list.
    // Caller paints the right pane separately (preview or editor).
    G->drawFastVLine(PANE_L_W, SB_H, SCREEN_HEIGHT - SB_H, C_HAIR);
#endif

    // appbar — back-to-Home chevron when launched from the Home launcher,
    // then the title shifts right to make room ("‹ Notes").
    int titleX = 14;
    if (s_fromHome) {
        int chx = 16, chy = APPBAR_Y + 11;
        if (s_backFocused) {   // double focus ring (matches Ui::focusRing)
            G->drawRoundRect(4, APPBAR_Y - 4, 34, 30, 8, C_ACCENT);
            G->drawRoundRect(5, APPBAR_Y - 3, 32, 28, 8, C_ACCENT);
        }
        uint16_t chColor = s_backFocused ? C_ACCENT : C_INK;
        G->drawWideLine(chx + 7, chy - 7, chx, chy, 2, chColor);
        G->drawWideLine(chx, chy, chx + 7, chy + 7, 2, chColor);
        titleX = 34;
    }
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fBig);
    G->setTextColor(C_INK);
    G->drawString("Notes", titleX, APPBAR_Y);
#if !COVER_NOTES_TWO_PANE
    // avatar (portrait layout only — no room / looks odd in the narrow left pane)
    int avr = 12, avx = SCREEN_WIDTH - 14 - avr, avy = APPBAR_Y + 6;
    G->fillSmoothCircle(avx, avy, avr, C_ACCENT);
    G->setFont(&s_fTitle);
    G->setTextColor(C_CARD);
    G->setTextDatum(textdatum_t::middle_center);
    G->drawString("A", avx, avy - 1);
    G->setTextDatum(textdatum_t::top_left);
#endif

    // search pill
    bool sfocus = s_searchFocused || s_searchActive;
    int searchW = LIST_W - 20;
    G->fillSmoothRoundRect(10, SEARCH_Y, searchW, SEARCH_H, 9, sfocus ? C_CARD : C_SEARCH);
    if (sfocus) {
        G->drawRoundRect(8, SEARCH_Y - 2, searchW + 4, SEARCH_H + 4, 10, C_ACCENT);
        G->drawRoundRect(9, SEARCH_Y - 1, searchW + 2, SEARCH_H + 2, 9, C_ACCENT);
    }
    int mcx = 26, mcy = SEARCH_Y + SEARCH_H / 2;   // magnifier
    G->drawCircle(mcx, mcy - 1, 4, C_MUTED);
    G->drawWideLine(mcx + 3, mcy + 2, mcx + 6, mcy + 5, 2, C_MUTED);
    G->setFont(&s_fBody);
    int qMaxW = searchW - 30 - 24;            // leave room for the clear-x
    if (s_query.length()) {
        drawClipped(s_query.c_str(), 40, SEARCH_Y + 5, qMaxW, C_INK);
        int xcx = LIST_W - 24, xcy = mcy;    // clear (x)
        G->drawWideLine(xcx - 4, xcy - 4, xcx + 4, xcy + 4, 2, C_MUTED);
        G->drawWideLine(xcx - 4, xcy + 4, xcx + 4, xcy - 4, 2, C_MUTED);
    } else {
        G->setTextColor(C_MUTED);
        G->drawString("Search", 40, SEARCH_Y + 5);
    }
    if (s_searchActive && caretOn) {
        int cxq = 41 + (s_query.length() ? G->textWidth(s_query.c_str()) : 0);
        if (cxq > 40 + qMaxW) cxq = 40 + qMaxW;
        G->fillRect(cxq, SEARCH_Y + 5, 2, 16, C_INK);
    }

    // scroll region
    G->setClipRect(0, LIST_TOP, LIST_W, SCREEN_HEIGHT - LIST_TOP);
    int base = LIST_TOP - scroll;
    int n = (int)s_filtered.size();
    char lbl[24];
    if (s_query.length()) snprintf(lbl, sizeof(lbl), "%d result%s", n, n == 1 ? "" : "s");
    else                  strcpy(lbl, "Notes");
    drawSectionLabel(lbl, base);
    if (n == 0) {
        G->setFont(&s_fBody);
        G->setTextColor(C_MUTED);
#if COVER_NOTES_TWO_PANE
        G->drawString(s_query.length() ? "No matching notes" :
#if BOARD_HAS_TOUCH
                      "No notes yet - tap + to add one",
#else
                      "No notes — click +",
#endif
                      CARD_X + 4, base + LABEL_H + 12);
#else
        G->drawString(s_query.length() ? "No matching notes" : "No notes yet - tap + to add one",
                      CARD_X + 4, base + LABEL_H + 12);
#endif
    } else {
        bool anySel = !s_searchFocused && !s_searchActive && !s_backFocused && !s_fabFocused;
        for (int pos = 0; pos < n; pos++) {
            int y = base + cardTop(pos);
            if (y > SCREEN_HEIGHT || y + CARD_H < LIST_TOP) continue;
            drawCard(s_filtered[pos], y, anySel && pos == sel);
        }
    }
    G->clearClipRect();

    // FAB (drawn last, floats over the list) — focus ring when encoder-selected
    if (s_fabFocused) G->fillSmoothCircle(FAB_CX, FAB_CY, FAB_R + 3, C_ACCENT);
    G->fillSmoothCircle(FAB_CX, FAB_CY, FAB_R, C_ACCENT);
    G->drawWideLine(FAB_CX - 9, FAB_CY, FAB_CX + 9, FAB_CY, 3, C_CARD);
    G->drawWideLine(FAB_CX, FAB_CY - 9, FAB_CX, FAB_CY + 9, 3, C_CARD);
}

// keep the selected card fully inside the scroll region
static int scrollToSel(int sel, int scroll) {
    int top = cardTop(sel);
    int bot = top + CARD_H;
    int viewH = SCREEN_HEIGHT - LIST_TOP;
    if (top - scroll < 0)            scroll = top;
    if (bot - scroll > viewH)        scroll = bot - viewH;
    if (scroll < 0) scroll = 0;
    if (scroll > maxScroll()) scroll = maxScroll();
    return scroll;
}

// which filtered card position is under a tap at screen-y (list view); -1 if none.
// Returns a position into s_filtered — caller maps to the real note via s_filtered[pos].
static int cardAtY(int tapY, int scroll) {
    if (tapY < LIST_TOP) return -1;
    int base = LIST_TOP - scroll;
    int n = (int)s_filtered.size();
    for (int pos = 0; pos < n; pos++) {
        int y = base + cardTop(pos);
        if (tapY >= y && tapY <= y + CARD_H) return pos;
    }
    return -1;
}

// tap inside the search pill? (and its clear-x sub-region on the right)
static bool tapSearch(int x, int y) {
    return y >= SEARCH_Y && y <= SEARCH_Y + SEARCH_H && x >= 10 && x <= LIST_W - 10;
}
static bool tapSearchClear(int x, int y) {
    int xcx = LIST_W - 24, xcy = SEARCH_Y + SEARCH_H / 2;
    return x >= xcx - 8 && x <= xcx + 8 && y >= xcy - 8 && y <= xcy + 8;
}

// ── DETAIL view — a real cursor-addressable editor ───────────────────────────
// Cursor is a (line, col) pair: line 0 = title, line 1..N = body[line-1]. This
// unifies title/body editing — moving the cursor UP out of the body naturally
// lands in the title, no separate "titling mode" needed.
// DOC_TOP / DOC_X / DOC_MAX_W defined with the layout macros above.

static String* vline(NoteRec& n, int vidx) {
    if (vidx == 0) return &n.title;
    int bi = vidx - 1;
    if (bi >= 0 && bi < (int)n.body.size()) return &n.body[bi];
    return nullptr;
}
static int vlineCount(const NoteRec& n) { return 1 + (int)n.body.size(); }

// One word-wrapped visual row. colStart is the column into the ORIGINAL
// (unwrapped) source line where this row begins — this is what lets cursor
// placement and touch hit-testing map back to a real character position even
// though the text on screen has been split across multiple rows.
struct LayoutRow {
    int    vline;
    int    colStart;
    String text;
    int    y;         // doc-relative (scroll-independent) y
    bool   isTitle;
};

// Pure layout, no drawing — word-wraps title+body into rows with exact column
// offsets. Returns total doc-relative content height. Reused for measuring
// (docMaxScroll), cursor placement (ensureCursorVisible), touch hit-testing
// (moveCursorToTap), and rendering (drawDetail calls this once then draws the
// rows it collected, avoiding a second wrap pass just to draw).
static int layoutNote(const NoteRec& n, std::vector<LayoutRow>& rows) {
    rows.clear();
    int x = DOC_X, maxW = DOC_MAX_W;
    int y = 0;

    G->setFont(&s_fTitle);
    rows.push_back({0, 0, n.title, y, true});
    y += 24;
    y += 18;   // meta line (line count) — fixed, not part of cursor addressing

    G->setFont(&s_fBody);
    for (int bi = 0; bi < (int)n.body.size(); bi++) {
        const String& src = n.body[bi];
        int vl = bi + 1;
        if (src.length() == 0) { rows.push_back({vl, 0, "", y, false}); y += 20; continue; }
        int len = src.length();
        int rowStart = 0, lastSpace = -1, i = 0;
        (void)x;
        while (i < len) {
            if (src[i] == ' ') lastSpace = i;
            String candidate = src.substring(rowStart, i + 1);
            if (G->textWidth(candidate.c_str()) > maxW && i > rowStart) {
                int breakAt = (lastSpace > rowStart) ? lastSpace : i;
                rows.push_back({vl, rowStart, src.substring(rowStart, breakAt), y, false});
                y += 20;
                rowStart = (lastSpace > rowStart) ? lastSpace + 1 : breakAt;
                lastSpace = -1;
                i = rowStart;
                continue;
            }
            i++;
        }
        rows.push_back({vl, rowStart, src.substring(rowStart, len), y, false});
        y += 20;
    }
    return y;
}

static void renderRows(const std::vector<LayoutRow>& rows, int scroll) {
    for (auto& r : rows) {
        if (r.text.length() == 0) continue;   // blank row — nothing to draw
        G->setFont(r.isTitle ? &s_fTitle : &s_fBody);
        int sy = DOC_TOP - scroll + r.y;
        if (r.isTitle) drawClipped(r.text.c_str(), DOC_X, sy, DOC_MAX_W, C_INK);
        else { G->setTextColor(C_INK); G->drawString(r.text, DOC_X, sy); }
    }
}

static int docMaxScroll(const NoteRec& n) {
    std::vector<LayoutRow> rows;
    int h = layoutNote(n, rows) + 8;
    int viewH = SCREEN_HEIGHT - DOC_TOP;
    return h > viewH ? h - viewH : 0;
}

// Adjusts docScroll (in place) so the row containing (curLine,curCol) is visible.
static void ensureCursorVisible(const NoteRec& n, int curLine, int curCol, int& docScroll) {
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    int rowY = 0, rowH = 20;
    for (auto& r : rows) {
        if (r.vline == curLine && curCol >= r.colStart && curCol <= r.colStart + (int)r.text.length()) {
            rowY = r.y; rowH = r.isTitle ? 24 : 20; break;
        }
    }
    int viewH = SCREEN_HEIGHT - DOC_TOP;
    if (rowY - docScroll < 0)         docScroll = rowY;
    if (rowY + rowH - docScroll > viewH) docScroll = rowY + rowH - viewH;
    if (docScroll < 0) docScroll = 0;
    int dm = docMaxScroll(n);
    if (docScroll > dm) docScroll = dm;
}

// Maps a tap (screen x/y) to the nearest (line, col) — "touch a line" support.
static void moveCursorToTap(const NoteRec& n, int tapX, int tapY, int scroll, int& curLine, int& curCol) {
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    int localY = tapY - DOC_TOP + scroll;
    const LayoutRow* best = nullptr; int bestDist = 0x7fffffff;
    for (auto& r : rows) {
        int rh = r.isTitle ? 24 : 20;
        if (localY >= r.y && localY < r.y + rh) { best = &r; break; }
        int d = abs(localY - r.y);
        if (d < bestDist) { bestDist = d; best = &r; }
    }
    if (!best) return;
    curLine = best->vline;
    G->setFont(best->isTitle ? &s_fTitle : &s_fBody);
    int tx = tapX - DOC_X;
    int col = (int)best->text.length();
    for (int ci = 0; ci <= (int)best->text.length(); ci++) {
        String prefix = best->text.substring(0, ci);
        if (G->textWidth(prefix.c_str()) >= tx) { col = ci; break; }
    }
    curCol = best->colStart + col;
}

static uint32_t s_saveNoticeMs = 0;   // "Saved"/"No SD" toast timer (save-icon tap)
static bool     s_saveNoticeOk = true;

#if COVER_NOTES_TWO_PANE
// Right-pane preview of the selected list card (VIEW_LIST). Empty state when none.
static void drawRightPreview(int sel) {
    G->fillRect(PANE_R_X, SB_H, PANE_R_W, SCREEN_HEIGHT - SB_H, C_PAPER);
    G->drawFastVLine(PANE_L_W, SB_H, SCREEN_HEIGHT - SB_H, C_HAIR);
    int n = (int)s_filtered.size();
    if (n <= 0 || sel < 0 || sel >= n || s_searchFocused || s_searchActive || s_backFocused || s_fabFocused) {
        G->setFont(&s_fBody);
        G->setTextColor(C_MUTED);
        G->setTextDatum(textdatum_t::middle_center);
        G->drawString(n <= 0 ? "Select or add a note" : "Preview",
                      PANE_R_X + PANE_R_W / 2, SB_H + (SCREEN_HEIGHT - SB_H) / 2);
        G->setTextDatum(textdatum_t::top_left);
        return;
    }
    const NoteRec& nrec = s_notes[s_filtered[sel]];
    G->setFont(&s_fTitle);
    G->setTextColor(C_INK);
    drawClipped(nrec.title.length() ? nrec.title.c_str() : "(untitled)",
                DOC_X, SB_H + 12, DOC_MAX_W, C_INK);
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    int lc = (int)nrec.body.size();
    char m[24]; snprintf(m, sizeof(m), "%d line%s", lc, lc == 1 ? "" : "s");
    G->drawString(m, DOC_X, SB_H + 34);
    G->setFont(&s_fBody);
    G->setTextColor(C_PREV);
    String prev = notePreview(nrec);
    // wrap a few preview lines into the right pane
    int y = SB_H + 56;
    String line;
    for (int i = 0; i < (int)prev.length() && y < SCREEN_HEIGHT - 16; i++) {
        char c = prev[i];
        String tryL = line + c;
        if (G->textWidth(tryL.c_str()) > DOC_MAX_W && line.length()) {
            G->drawString(line, DOC_X, y); y += 18; line = String(c);
        } else line = tryL;
    }
    if (line.length() && y < SCREEN_HEIGHT - 16) G->drawString(line, DOC_X, y);
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    G->setTextDatum(textdatum_t::middle_center);
    G->drawString("Click to open", PANE_R_X + PANE_R_W / 2, SCREEN_HEIGHT - 14);
    G->setTextDatum(textdatum_t::top_left);
}
#endif

static void drawDetail(const NoteRec& n, int scroll, int curLine, int curCol, bool cursorOn) {
#if COVER_NOTES_TWO_PANE
    // Editor lives in the right pane only — left list is painted by the caller.
    G->fillRect(PANE_R_X, SB_H, PANE_R_W, SCREEN_HEIGHT - SB_H, C_PAPER);
    G->drawFastVLine(PANE_L_W, SB_H, SCREEN_HEIGHT - SB_H, C_HAIR);
    int barY = SB_H, barH = 26;
    G->drawFastHLine(PANE_R_X, barY + barH - 1, PANE_R_W, C_HAIR);
    int cvx = PANE_R_X + 12, cvy = barY + barH / 2;
    G->drawWideLine(cvx + 5, cvy - 5, cvx, cvy, 2, C_ACCENT);
    G->drawWideLine(cvx, cvy, cvx + 5, cvy + 5, 2, C_ACCENT);
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fTitle);
    G->setTextColor(C_ACCENT);
    G->drawString("Edit", cvx + 12, barY + 5);
    int dx2 = SCREEN_WIDTH - 18;
    G->drawRoundRect(dx2 - 7, cvy - 7, 14, 14, 2, C_ACCENT);
    G->fillRect(dx2 - 4, cvy - 7, 8, 5, C_ACCENT);
    G->drawFastHLine(dx2 - 5, cvy + 2, 10, C_ACCENT);
    if (millis() - s_saveNoticeMs < 1200) {
        G->setFont(&s_fMeta);
        G->setTextColor(s_saveNoticeOk ? C_SAVED : C_ACCENT);
        G->setTextDatum(textdatum_t::middle_right);
        G->drawString(s_saveNoticeOk ? "Saved" : "No SD", dx2 - 12, cvy);
        G->setTextDatum(textdatum_t::top_left);
    }
    G->setClipRect(PANE_R_X, DOC_TOP, PANE_R_W, SCREEN_HEIGHT - DOC_TOP);
#else
    G->fillRect(0, SB_H, SCREEN_WIDTH, SCREEN_HEIGHT - SB_H, C_PAPER);

    // back bar
    int barY = SB_H, barH = 34;
    G->drawFastHLine(0, barY + barH - 1, SCREEN_WIDTH, C_HAIR);
    // chevron
    int cvx = 16, cvy = barY + barH / 2;
    G->drawWideLine(cvx + 5, cvy - 5, cvx, cvy, 2, C_ACCENT);
    G->drawWideLine(cvx, cvy, cvx + 5, cvy + 5, 2, C_ACCENT);
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fTitle);
    G->setTextColor(C_ACCENT);
    G->drawString("Notes", cvx + 12, barY + 8);

    // share icon (decorative, unchanged)
    int iy = cvy;
    int sx = SCREEN_WIDTH - 58;
    G->fillSmoothCircle(sx,     iy - 5, 2, C_ACCENT);
    G->fillSmoothCircle(sx - 8, iy,     2, C_ACCENT);
    G->fillSmoothCircle(sx,     iy + 5, 2, C_ACCENT);
    G->drawWideLine(sx - 7, iy - 1, sx - 1, iy - 4, 1, C_ACCENT);
    G->drawWideLine(sx - 7, iy + 1, sx - 1, iy + 4, 1, C_ACCENT);

    // SAVE button (was a decorative "download" icon — now functional: floppy glyph)
    int dx2 = SCREEN_WIDTH - 24;
    G->drawRoundRect(dx2 - 7, iy - 7, 14, 14, 2, C_ACCENT);
    G->fillRect(dx2 - 4, iy - 7, 8, 5, C_ACCENT);
    G->drawFastHLine(dx2 - 5, iy + 2, 10, C_ACCENT);

    if (millis() - s_saveNoticeMs < 1200) {
        G->setFont(&s_fMeta);
        G->setTextColor(s_saveNoticeOk ? C_SAVED : C_ACCENT);
        G->setTextDatum(textdatum_t::middle_right);
        G->drawString(s_saveNoticeOk ? "Saved" : "No SD", dx2 - 12, iy);
        G->setTextDatum(textdatum_t::top_left);
    }

    // doc body, clipped + scrolled
    G->setClipRect(0, DOC_TOP, SCREEN_WIDTH, SCREEN_HEIGHT - DOC_TOP);
#endif
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    renderRows(rows, scroll);

    // meta line (line count) — fixed doc-relative y=24, under the title
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    int lc = (int)n.body.size();
    char m[24]; snprintf(m, sizeof(m), "%d line%s", lc, lc == 1 ? "" : "s");
    G->drawString(m, DOC_X, DOC_TOP - scroll + 24);

    if (cursorOn) {
        for (auto& r : rows) {
            if (r.vline == curLine && curCol >= r.colStart && curCol <= r.colStart + (int)r.text.length()) {
                G->setFont(r.isTitle ? &s_fTitle : &s_fBody);
                String prefix = r.text.substring(0, curCol - r.colStart);
                int cx = DOC_X + G->textWidth(prefix.c_str());
                int cy = DOC_TOP - scroll + r.y;
                int ch = r.isTitle ? 18 : 16;
                G->fillRect(cx, cy, 2, ch, C_INK);
                break;
            }
        }
    }
    G->clearClipRect();
}

// tap on the back chevron/"Notes" region of the detail bar?
static bool tapBack(int x, int y) {
#if COVER_NOTES_TWO_PANE
    return y >= SB_H && y <= SB_H + 28 && x >= PANE_R_X && x <= PANE_R_X + 80;
#else
    return y >= SB_H && y <= SB_H + 34 && x <= 80;
#endif
}
// tap on the save-button icon?
static bool tapSave(int x, int y) {
    int dx2 = SCREEN_WIDTH - 24, iy = SB_H + 34 / 2;
#if COVER_NOTES_TWO_PANE
    dx2 = SCREEN_WIDTH - 18; iy = SB_H + 13;
#endif
    return x >= dx2 - 12 && x <= dx2 + 8 && y >= iy - 12 && y <= iy + 12;
}

// Compose a full frame into the canvas, then blit once (no flicker).
static void paintList(int scroll, int sel, bool caretOn = true) {
    drawStatusBar();
    drawList(scroll, sel, caretOn);
#if COVER_NOTES_TWO_PANE
    drawRightPreview(sel);
#endif
    cover::flush();
}
static void paintDetail(const NoteRec& n, int ds, int curLine, int curCol, bool cursorOn) {
    drawStatusBar();
#if COVER_NOTES_TWO_PANE
    // Keep the left list visible beside the editor.
    int idx = -1, listSel = 0;
    for (int i = 0; i < (int)s_notes.size(); i++) if (&s_notes[i] == &n) { idx = i; break; }
    for (int i = 0; i < (int)s_filtered.size(); i++) if (s_filtered[i] == idx) { listSel = i; break; }
    s_fabFocused = false; s_searchFocused = false; s_backFocused = false; s_searchActive = false;
    drawList(0, listSel, false);
#endif
    drawDetail(n, ds, curLine, curCol, cursorOn);
    cover::flush();
}

// The secret-passphrase rolling buffer lives in cover_kit (shared with home_ui):
// it accumulates the last ucPhraseLen() printable keystrokes typed anywhere in the
// cover and matches the tail against the stored hash — no visual feedback.
static uint32_t s_lastTapMs = 0;   // double-tap state for screen-off wake

// ── Entry point ──────────────────────────────────────────────────────────────
bool runNotesUi(bool standalone) {
    // Full-screen PSRAM back-buffer + baked fonts (shared cover shell). Sets cover::G
    // (aliased as G) so every draw lands in the sprite; falls back to the panel if the
    // PSRAM sprite can't be allocated.
    cover::setupCanvas();
    initColors();
    // Suppress the real AL-ANQA status bar (ClockManager/battery redraws at y<30):
    // setBlocked no-ops DisplayManager output; we draw the whole screen ourselves,
    // exactly like the lock screen does while blocked. This is what the cover does.
    displayManager.setBlocked(true);

    // Fresh state each session.
    cover::resetPassphrase(); s_lastTapMs = 0; s_saveNoticeMs = 0; s_saveNoticeOk = true;
    s_fromHome = !standalone;   // launched from Home → show the back-to-Home chevron

    // Fresh search state each session, then build the (initially unfiltered) set.
    s_query = ""; s_searchActive = false; s_searchFocused = false; s_backFocused = false; s_fabFocused = false;

    loadNotesFromSD();
    rebuildFilter();

    int  view = VIEW_LIST, sel = 0, scroll = 0, cur = -1, docScroll = 0;
    int  curLine = 0, curCol = 0;   // cursor: 0=title, 1..N=body[line-1]
    bool cursorOn = true;
    bool secretExit = false;   // set iff we leave via the secret passphrase
    uint32_t lastBlinkMs = millis();

    // Saves the open note if it has real content; otherwise drops a never-typed
    // placeholder (created by FAB-tap) so it doesn't leave a ghost list row.
    auto leaveDetail = [&]() {
        if (cur >= 0 && cur < (int)s_notes.size()) {
            NoteRec& n = s_notes[cur];
            if (n.dirty)                    saveNote(n);
            else if (n.path.length() == 0)  s_notes.erase(s_notes.begin() + cur);
        }
        // The note may have been edited (title now (mis)matches the query) or a
        // placeholder erased — rebuild the result set and re-clamp sel/scroll.
        rebuildFilter();
        if (sel >= (int)s_filtered.size()) sel = (int)s_filtered.size() - 1;
        if (sel < 0) sel = 0;
        if (scroll > maxScroll()) scroll = maxScroll();
        view = VIEW_LIST; cur = -1;
        paintList(scroll, sel);
    };

    paintList(scroll, sel);

    TouchManager& tm = TouchManager::instance();

    bool     s_wasDimmed = false;
    uint32_t lastStatusMs = millis();

    while (true) {
        if (LockScreenManager::getInstance().consumeJustUnlocked()) {
            displayManager.setBlocked(true);
            if (view == VIEW_LIST) paintList(scroll, sel);
            else if (cur >= 0)     paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
        }

        // While actually locked (LockScreenManager's OWN idle timer, independent of
        // undercover), its dormant screen draws directly to tft (setBlocked(false)
        // around itself) — bypassing our sprite compositing entirely. If we keep
        // painting/polling touch here too, its 1s duration-counter tick (real AL-ANQA
        // status bar + "Locked: HH:MM:SS") leaks onto the panel and stays visible
        // until our next repaint. So: stand down completely and let it own the
        // screen, same as wguard/buddy do via isBlocked() — just keep pumping
        // getKeyboardInput() so PIN entry works and consumeJustUnlocked() fires the
        // moment it unlocks (handled above, next loop iteration).
        if (LockScreenManager::getInstance().isLocked()) {
            inputHandler.getKeyboardInput();
            vTaskDelay(pdMS_TO_TICKS(10));
            continue;
        }

        // Repaint after any dim→wake transition so the terminal never bleeds through.
        // The panel may have been partially redrawn (clock/status updates) while dim;
        // the sprite blit restores the cover atomically.
        {
            bool dimmed = PowerSaveManager::getInstance().isDimmed();
            if (s_wasDimmed && !dimmed) {
                displayManager.setBlocked(true);
                if (view == VIEW_LIST) paintList(scroll, sel);
                else if (cur >= 0)     paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
            s_wasDimmed = dimmed;
        }

        // Live status bar: repaint the current view every 20s so the clock ticks and
        // the battery/charging state stay current while idle (matches the home cover).
        if (millis() - lastStatusMs >= 20000) {
            lastStatusMs = millis();
            if (view == VIEW_LIST) paintList(scroll, sel);
            else if (cur >= 0)     paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
        }

        // Cursor blink while a note is open for editing — repaints every 500ms so
        // the caret visibly blinks even with no new input. Same blink drives the
        // search-box caret while the query is being typed in the list view.
        if (view == VIEW_DETAIL && cur >= 0 && cur < (int)s_notes.size()) {
            uint32_t now = millis();
            if (now - lastBlinkMs >= 500) {
                lastBlinkMs = now;
                cursorOn = !cursorOn;
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
        } else if (view == VIEW_LIST && s_searchActive) {
            uint32_t now = millis();
            if (now - lastBlinkMs >= 500) {
                lastBlinkMs = now;
                cursorOn = !cursorOn;
                paintList(scroll, sel, cursorOn);
            }
        }

        // ── touch ──
        // Power-save wake lives HERE — main.ino's loop is blocked while we run.
        TouchEvent te = tm.poll();
        cover::handleTouchWake(te, s_lastTapMs);   // screen-off double-tap / half-dim wake

        if (view == VIEW_LIST) {
            if (te.type == TouchEvent::TAP) {
                // Back-to-Home chevron (left of the appbar) — only when launched
                // from the Home launcher. Returns to Home (not the CLI).
                if (s_fromHome && te.y >= SB_H && te.y < SEARCH_Y && te.x <= 44) {
                    secretExit = false;
                    break;
                }
                // Search pill — tap to focus + start editing; tap the x to clear.
                if (tapSearch(te.x, te.y)) {
                    if (s_query.length() && tapSearchClear(te.x, te.y)) {
                        s_query = ""; rebuildFilter(); sel = 0; scroll = 0;
                    }
                    s_searchActive = true; s_searchFocused = true; s_backFocused = false; s_fabFocused = false;
                    cursorOn = true; lastBlinkMs = millis();
                    paintList(scroll, sel, cursorOn);
                } else {
                    // Tapping anywhere else drops search-edit / back focus.
                    bool wasFocused = s_searchActive || s_searchFocused || s_backFocused || s_fabFocused;
                    s_searchActive = false; s_searchFocused = false; s_backFocused = false; s_fabFocused = false;
                    int dx = te.x - FAB_CX, dy = te.y - FAB_CY;
                    if (dx * dx + dy * dy <= (FAB_R + 4) * (FAB_R + 4)) {
                        // New note — clear any active query so the fresh note is visible.
                        s_query = "";
                        s_notes.insert(s_notes.begin(), NoteRec());
                        rebuildFilter();
                        cur = 0; sel = 0; docScroll = 0; curLine = 0; curCol = 0; cursorOn = true;
                        view = VIEW_DETAIL; paintDetail(s_notes[cur], 0, curLine, curCol, cursorOn);
                    } else {
                        int hit = cardAtY(te.y, scroll);
                        if (hit >= 0) {
                            cur = s_filtered[hit]; sel = hit; cursorOn = true;
                            NoteRec& nn = s_notes[cur];
                            curLine = vlineCount(nn) - 1;
                            String* ls = vline(nn, curLine);
                            curCol = ls ? (int)ls->length() : 0;
                            docScroll = docMaxScroll(nn);   // open at the end — continue typing
                            view = VIEW_DETAIL; paintDetail(nn, docScroll, curLine, curCol, cursorOn);
                        } else if (wasFocused) {
                            paintList(scroll, sel);   // repaint to drop the pill's accent ring
                        }
                    }
                }
            } else if (te.type == TouchEvent::DRAG_MOVE) {
                scroll -= te.dy;
                if (scroll < 0) scroll = 0;
                if (scroll > maxScroll()) scroll = maxScroll();
                paintList(scroll, sel);
            }
        } else { // VIEW_DETAIL
            if (te.type == TouchEvent::TAP && cur >= 0 && tapSave(te.x, te.y)) {
                if (s_notes[cur].dirty) {
                    s_saveNoticeOk = saveNote(s_notes[cur]);
                    s_saveNoticeMs = millis();
                } else if (s_notes[cur].path.length() > 0) {
                    s_saveNoticeOk = true;   // already on disk, nothing new to write
                    s_saveNoticeMs = millis();
                }
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            } else if (te.type == TouchEvent::TAP && tapBack(te.x, te.y)) {
                leaveDetail();
            } else if (te.type == TouchEvent::TAP && cur >= 0) {
                // Touch a line — cursor jumps there ("fix a word" support).
                moveCursorToTap(s_notes[cur], te.x, te.y, docScroll, curLine, curCol);
                ensureCursorVisible(s_notes[cur], curLine, curCol, docScroll);
                cursorOn = true; lastBlinkMs = millis();
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            } else if (te.type == TouchEvent::DRAG_MOVE && cur >= 0) {
                docScroll -= te.dy;
                int dm = docMaxScroll(s_notes[cur]);
                if (docScroll < 0) docScroll = 0;
                if (docScroll > dm) docScroll = dm;
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
        }

        // ── trackball ──
        // 300ms throttle — raw events fire far faster than deliberate movement.
        // List:   UP/DOWN = navigate cards · CLICK = open note
        // Detail: UP/DOWN/LEFT/RIGHT = move the cursor (LEFT/RIGHT wrap across
        //         lines; UP out of body line 0 lands in the title) · CLICK = back
        //         to list (saves) — the only back-trigger now that LEFT moves
        //         the cursor.
        TrackballEvent tb = inputHandler.getTrackballEvent();
        static uint32_t s_lastTbMs = 0;
        if (tb != TBALL_NONE) {
            uint32_t now = millis();
            if (now - s_lastTbMs >= 300) {
                s_lastTbMs = now;
                if (view == VIEW_LIST) {
                    int n = (int)s_filtered.size();
                    if (s_searchActive) {
                        // Editing the query: CLICK confirms (keeps filter+focus),
                        // DOWN drops into the result list.
                        if (tb == TBALL_CLICK) { s_searchActive = false; paintList(scroll, sel); }
                        else if (tb == TBALL_DOWN) {
                            s_searchActive = false; s_searchFocused = false;
                            sel = 0; scroll = 0; paintList(scroll, sel);
                        }
                    } else if (s_fabFocused) {
                        // + FAB highlighted: CLICK creates a note; UP returns to the last card
                        // (or the search pill when the list is empty).
                        if (tb == TBALL_CLICK) {
                            s_fabFocused = false;
                            s_query = "";
                            s_notes.insert(s_notes.begin(), NoteRec());
                            rebuildFilter();
                            cur = 0; sel = 0; docScroll = 0; curLine = 0; curCol = 0; cursorOn = true;
                            view = VIEW_DETAIL; paintDetail(s_notes[cur], 0, curLine, curCol, cursorOn);
                        } else if (tb == TBALL_UP) {
                            s_fabFocused = false;
                            if (n > 0) { sel = n - 1; scroll = scrollToSel(sel, scroll); }
                            else       { s_searchFocused = true; }
                            paintList(scroll, sel);
                        }
                    } else if (s_backFocused) {
                        // Back-to-Home chevron highlighted: CLICK returns to Home
                        // (same as tapping it); DOWN drops back to the search pill.
                        if (tb == TBALL_CLICK) { secretExit = false; break; }
                        else if (tb == TBALL_DOWN) {
                            s_backFocused = false; s_searchFocused = true; paintList(scroll, sel);
                        }
                    } else if (s_searchFocused) {
                        // Pill highlighted (not yet editing): CLICK to edit, DOWN to list,
                        // UP to the back chevron (only when launched from Home).
                        if (tb == TBALL_CLICK) {
                            s_searchActive = true; cursorOn = true; lastBlinkMs = millis();
                            paintList(scroll, sel, cursorOn);
                        } else if (tb == TBALL_UP && s_fromHome) {
                            s_searchFocused = false; s_backFocused = true; paintList(scroll, sel);
                        } else if (tb == TBALL_DOWN) {
                            s_searchFocused = false;
                            if (n > 0) { sel = 0; scroll = scrollToSel(sel, scroll); }
                            else       { s_fabFocused = true; }
                            paintList(scroll, sel);
                        }
                    } else if (tb == TBALL_DOWN) {
                        if (sel < n - 1) {
                            sel++; scroll = scrollToSel(sel, scroll);
                            paintList(scroll, sel);
                        } else {
                            // past the last card (or empty list) → focus the + FAB
                            s_fabFocused = true; paintList(scroll, sel);
                        }
                    } else if (tb == TBALL_UP) {
                        if (sel > 0) {
                            sel--; scroll = scrollToSel(sel, scroll);
                            paintList(scroll, sel);
                        } else {
                            // at the top card — one more UP moves focus to the search pill
                            s_searchFocused = true; paintList(scroll, sel);
                        }
                    } else if (tb == TBALL_CLICK && n > 0) {
                        cur = s_filtered[sel]; cursorOn = true;
                        NoteRec& nn = s_notes[cur];
                        curLine = vlineCount(nn) - 1;
                        String* ls = vline(nn, curLine);
                        curCol = ls ? (int)ls->length() : 0;
                        docScroll = docMaxScroll(nn);
                        view = VIEW_DETAIL; paintDetail(nn, docScroll, curLine, curCol, cursorOn);
                    }
                } else if (cur >= 0) { // VIEW_DETAIL
                    if (tb == TBALL_CLICK) {
                        leaveDetail();
                    } else {
                        NoteRec& n = s_notes[cur];
                        int maxLine = vlineCount(n) - 1;
                        bool moved = false;
                        if (tb == TBALL_UP && curLine > 0) {
                            curLine--;
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol > len) curCol = len;
                            moved = true;
                        } else if (tb == TBALL_DOWN && curLine < maxLine) {
                            curLine++;
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol > len) curCol = len;
                            moved = true;
                        } else if (tb == TBALL_LEFT) {
                            if (curCol > 0) { curCol--; moved = true; }
                            else if (curLine > 0) {
                                curLine--;
                                String* ls = vline(n, curLine);
                                curCol = ls ? (int)ls->length() : 0;
                                moved = true;
                            }
                        } else if (tb == TBALL_RIGHT) {
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol < len) { curCol++; moved = true; }
                            else if (curLine < maxLine) { curLine++; curCol = 0; moved = true; }
                        }
                        if (moved) {
                            ensureCursorVisible(n, curLine, curCol, docScroll);
                            cursorOn = true; lastBlinkMs = millis();
                            paintDetail(n, docScroll, curLine, curCol, cursorOn);
                        }
                    }
                }
            }
        }

        // ── keyboard ──
        char k = inputHandler.getKeyboardInput();

        // Secret-passphrase check: accumulate printable keys into a sliding window
        // of ucPhraseLen() chars and compare the hash after every keypress. No
        // feedback — match silently exits the cover exactly like typing a memo.
        // OPSEC: on match we deliberately do NOT save the currently-open note —
        // the phrase characters were just typed into its title/body in earlier
        // loop iterations (before we could know a match was imminent), so saving
        // now would write the passphrase itself into a plaintext .txt on the SD
        // card. Skipping the save keeps the hash the ONLY place it ever exists.
        if (cover::feedPassphrase(k)) { secretExit = true; break; }

        // Search box editing — capture keystrokes into the query and live-filter
        // the list. Trackball-focusing the pill and then typing a printable key
        // auto-activates edit mode (Android-like). Runs AFTER the passphrase check
        // (so a phrase typed here still exits the cover) but BEFORE the q-exits, and
        // `continue`s on any real key so 'q' is a normal search character while
        // editing, never a back/exit.
        if (view == VIEW_LIST &&
            (s_searchActive || (s_searchFocused && (k == '\x08' || k == '\x7F' || (k >= 0x20 && k < 0x7F))))) {
            s_searchActive = true;
            bool changed = false;
            if (k == '\x08' || k == '\x7F') {
                if (s_query.length()) { s_query.remove(s_query.length() - 1); changed = true; }
            } else if (k == '\r' || k == '\n') {
                s_searchActive = false;          // confirm — keep the filter + pill focus
                paintList(scroll, sel);
            } else if (k >= 0x20 && k < 0x7F) {
                if (s_query.length() < 32) { s_query += k; changed = true; }
            }
            if (changed) {
                rebuildFilter();
                sel = 0; scroll = 0;
                cursorOn = true; lastBlinkMs = millis();
                paintList(scroll, sel, cursorOn);
            }
            if (k != 0) { vTaskDelay(pdMS_TO_TICKS(5)); continue; }
        }

        // Launched from the Home launcher: [q] in the LIST view steps back to Home
        // (returns false = not a covert exit), regardless of passphrase — returning
        // to the disguise launcher is not a CLI reveal. Runs AFTER the passphrase
        // check so a phrase containing 'q' still completes first. In DETAIL view 'q'
        // stays a typeable character — back out to the list (back chevron) first.
        if (!standalone && view == VIEW_LIST && !s_searchActive && (k == 'q' || k == 'Q')) {
            secretExit = false;
            break;
        }

        if ((k == 'q' || k == 'Q') && !s_searchActive && !ucHasPassphrase()) {
            // Fallback exit (only reachable with no passphrase configured — no
            // secret to protect here, so saving the open note is safe.
            if (cur >= 0 && cur < (int)s_notes.size() && s_notes[cur].dirty) saveNote(s_notes[cur]);
            break;
        }

        // Typing — inserts/deletes at (curLine, curCol), not just at the end, so
        // any line (including the title) can be edited after moving the cursor
        // there via touch or trackball.
        if (view == VIEW_DETAIL && cur >= 0 && cur < (int)s_notes.size()) {
            NoteRec& n = s_notes[cur];
            bool changed = false;
            if (k == '\x08' || k == '\x7F') {                        // backspace
                String* ls = vline(n, curLine);
                if (ls) {
                    if (curCol > 0) {
                        ls->remove(curCol - 1, 1);
                        curCol--; changed = true;
                    } else if (curLine > 0) {
                        // merge this line into the end of the previous one
                        String tail = *ls;                     // copy before any vector mutation
                        int prevLine = curLine - 1;
                        String* prev = vline(n, prevLine);
                        if (prev) {
                            int mergeCol = prev->length();
                            *prev += tail;
                            int bi = curLine - 1;
                            if (bi >= 0 && bi < (int)n.body.size()) n.body.erase(n.body.begin() + bi);
                            curLine = prevLine; curCol = mergeCol;
                            changed = true;
                        }
                    }
                }
            } else if (k == '\r' || k == '\n') {                     // enter — split at cursor
                String* ls = vline(n, curLine);
                if (ls) {
                    String tail = ls->substring(curCol);
                    *ls = ls->substring(0, curCol);
                    if (curLine == 0) {
                        n.body.insert(n.body.begin(), tail);
                        curLine = 1; curCol = 0;
                    } else {
                        int bi = curLine - 1;
                        n.body.insert(n.body.begin() + bi + 1, tail);
                        curLine++; curCol = 0;
                    }
                    changed = true;
                }
            } else if (k >= 0x20 && k < 0x7F) {                      // printable — insert at cursor
                String* ls = vline(n, curLine);
                int cap = (curLine == 0) ? 40 : 200;
                if (ls && (int)ls->length() < cap) {
                    *ls = ls->substring(0, curCol) + String(k) + ls->substring(curCol);
                    curCol++; changed = true;
                }
            }
            if (changed) {
                n.dirty = true;
                ensureCursorVisible(n, curLine, curCol, docScroll);
                cursorOn = true; lastBlinkMs = millis();
                paintDetail(n, docScroll, curLine, curCol, cursorOn);
            }
        }
    }

    // Tear down our own resources either way.
    s_notes.clear(); s_notes.shrink_to_fit();
    cover::teardownCanvas();   // free sprite + fonts, restore panel/Font0

    // When launched from the Home launcher (standalone=false) the caller still owns
    // the screen: leave setBlocked(true) and do NOT touch the CLI, so Home can
    // recreate its sprite and repaint without a terminal flash. Home inspects the
    // return value and, on a secret-passphrase exit, propagates the covert exit to
    // the CLI itself.
    if (standalone) {
        displayManager.setBlocked(false);
        displayManager.clearScreen();
        displayManager.setCursor(10, outputY);
        displayManager.printCommandScreen();
        // If we were panic-hidden mid-command, the command's static UI was blanked by
        // the cover. Raise the unlock-style repaint signal so it fully redraws on its
        // next loop (every consumeJustUnlocked-aware command: ws, sw, wguard, ...).
        LockScreenManager::getInstance().signalRedraw();
    }
    return secretExit;
}
