#!/usr/bin/env python3
# Bakes anti-aliased VLW smooth fonts for the undercover Notes UI (notes_ui.cpp).
# Emits t-rex-firmware/core/system/undercover/notes_fonts.h — four Noto Sans
# faces (Android's font family) as embedded byte arrays LovyanGFX loads via
# VLWfont::loadFont / PointerWrapper.
#
# VLW format (verified against LovyanGFX lgfx_fonts.cpp VLWfont::loadFont):
#   header  : 6x uint32 BE = [gCount, version(11), fontSizePx, 0, ascent, descent]
#   glyph[] : 7x uint32 BE = [unicode, height, width, xAdvance, dY, gdX, 0]
#             (sorted by unicode ascending; dY = baseline->glyph-top, +up)
#   bitmaps : per glyph, width*height bytes of 8-bit alpha, row-major top-down
#
# Runs as a PlatformIO pre-script OR standalone (python3 convert_font.py).
# BEST-EFFORT: if Pillow or the TTFs are missing it no-ops and leaves the
# committed header in place, so fresh clones / CI still build.

import os, sys, struct

try:
    Import("env")                       # noqa — PlatformIO/SCons built-in
    _project_dir = env.subst("$PROJECT_DIR")
except NameError:
    _project_dir = os.path.dirname(os.path.abspath(__file__))

HEADER_PATH = os.path.join(_project_dir, "t-rex-firmware", "core", "system",
                           "undercover", "notes_fonts.h")

# Candidate locations for Noto Sans Regular/Bold (Debian/Ubuntu, Fedora, repo).
_NOTO_REG = ["/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
             "/usr/share/fonts/google-noto/NotoSans-Regular.ttf"]
_NOTO_BLD = ["/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf",
             "/usr/share/fonts/google-noto/NotoSans-Bold.ttf"]

def _find(paths):
    for p in paths:
        if os.path.isfile(p):
            return p
    return None

# (C array name, weight, pixel size)
FONTS = [
    ("NOTES_FONT_BIG",   "bold", 20),   # app title "Notes"
    ("NOTES_FONT_TITLE", "bold", 15),   # card titles, detail title, back label
    ("NOTES_FONT_BODY",  "reg",  14),   # preview, note body, checklist, search
    ("NOTES_FONT_META",  "reg",  11),   # meta lines, section labels
]

FIRST, LAST = 0x21, 0x7E   # printable ASCII except space (0x20 is special-cased in LGFX)

def build_vlw(ttf_path, px):
    from PIL import Image, ImageDraw, ImageFont
    font = ImageFont.truetype(ttf_path, px)
    ascent, descent = font.getmetrics()

    glyphs = []          # (unicode, w, h, advance, dY, gdX, alpha_bytes)
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        l, t, r, b = font.getbbox(ch)          # anchor 'la': origin at ascender-top
        w, h = r - l, b - t
        adv = max(0, min(255, round(font.getlength(ch))))
        if w <= 0 or h <= 0:                    # zero-ink glyph — advance only
            glyphs.append((cp, 0, 0, adv, 0, 0, b""))
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-l, -t), ch, fill=255, font=font)
        gdX = max(-128, min(127, l))            # left bearing (int8)
        dY  = ascent - t                        # baseline -> glyph top, +up
        glyphs.append((cp, w, h, adv, dY, gdX, img.tobytes()))

    glyphs.sort(key=lambda g: g[0])             # LGFX binary-searches gUnicode

    out = bytearray()
    out += struct.pack(">6I", len(glyphs), 11, px, 0, ascent, descent)
    for cp, w, h, adv, dY, gdX, _ in glyphs:
        out += struct.pack(">I", cp)
        out += struct.pack(">I", h)
        out += struct.pack(">I", w)
        out += struct.pack(">I", adv)
        out += struct.pack(">i", dY)            # signed low 16 read by LGFX
        out += struct.pack(">i", gdX)           # signed low 8 read by LGFX
        out += struct.pack(">I", 0)
    for g in glyphs:
        out += g[6]
    return bytes(out)

def emit_array(name, data):
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join("0x%02X" % b for b in data[i:i+16])
        lines.append("  " + chunk + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    try:
        import PIL  # noqa
    except Exception:
        print("convert_font: Pillow not available — keeping committed notes_fonts.h")
        return
    reg, bld = _find(_NOTO_REG), _find(_NOTO_BLD)
    if not reg or not bld:
        print("convert_font: Noto Sans TTFs not found — keeping committed notes_fonts.h")
        return

    blocks = []
    for name, weight, px in FONTS:
        data = build_vlw(bld if weight == "bold" else reg, px)
        blocks.append(emit_array(name, data))
        print(f"convert_font: {name} ({weight} {px}px) -> {len(data)} bytes")

    body = "\n\n".join(blocks)
    header = (
        "// Auto-generated by convert_font.py — DO NOT EDIT.\n"
        "// Anti-aliased VLW smooth fonts (Noto Sans) for the undercover Notes UI.\n"
        "// Source: Noto Sans (SIL Open Font License 1.1), Google.\n"
        "#ifndef NOTES_FONTS_H\n#define NOTES_FONTS_H\n\n"
        "#include <cstdint>\n\n"
        f"{body}\n\n"
        "#endif // NOTES_FONTS_H\n"
    )
    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w") as f:
        f.write(header)
    print(f"convert_font: wrote {HEADER_PATH}")

main()
