// T-REX — offensive security firmware for LilyGo T-DECK
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Abdallah Natsheh
//
// Notes cover UI — Phase 2. Visual spec + palette from the approved mockup
// (trex-undercover-notes.html); mockup is drawn 2x, real px = mockup / 2.
// Draws directly to the global LGFX (like buddy/editor). Text uses anti-aliased
// Noto Sans (Android's font family) baked to VLW smooth fonts — notes_fonts.h,
// generated by convert_font.py — for a modern, non-terminal look.
//
// Notes are REAL: /notes/*.txt on SD (root-level, outside /apps — see
// SD_DIR_NOTES). Line 1 = title, remaining lines = body (plain text, no
// checklist support — this is a keyboard-typable notes app, not a demo).
// No SD → falls back to an in-RAM starter set; edits don't persist (session-only,
// same "No SD" degrade pattern used everywhere else in this firmware).

#include "notes_ui.h"
#include "undercover_config.h"
#include "display_manager.h"
#include "input_handling.h"
#include "touch_manager.h"
#include "lockscreen_manager.h"
#include "powersave_manager.h"
#include "sdcard_manager.h"
#include "notes_fonts.h"      // baked Noto Sans VLW smooth fonts (convert_font.py)
#include <Arduino.h>
#include <SD.h>
#include <vector>
#include <algorithm>

extern LGFX           tft;
extern DisplayManager displayManager;
extern InputHandling  inputHandler;
extern SDCardManager  sdCardManager;

// ── Double buffering ────────────────────────────────────────────────────────
// Every touch/drag event repaints the whole view; drawing that straight to the
// panel shows the clear→redraw as flicker. So all draw calls go through `G`,
// which points at a full-screen PSRAM sprite; each frame is composed off-screen
// then blitted in one pushSprite (same pattern as csidetect's radar). If the
// PSRAM sprite can't be allocated, G falls back to the panel (flickers, but
// still works).
static LGFX_Sprite      s_canvas(&tft);
static lgfx::LovyanGFX* G = &tft;
static bool             s_haveCanvas = false;

static void flushCanvas() {
    if (s_haveCanvas) s_canvas.pushSprite(&tft, 0, 0);
}

// ── Anti-aliased smooth fonts (Noto Sans, baked to VLW) ─────────────────────
// Held as persistent VLWfont objects loaded once per session — switching with
// setFont() then costs nothing (no re-parse). PointerWrapper reads the glyph
// data straight from the flash array via memcpy_P. F_BIG=app title, F_TITLE=
// card/detail titles, F_BODY=preview/body, F_META=meta/section labels.
static lgfx::VLWfont        s_fBig, s_fTitle, s_fBody, s_fMeta;
static lgfx::PointerWrapper s_wBig, s_wTitle, s_wBody, s_wMeta;
static bool                 s_fontsLoaded = false;

static void loadFonts() {
    if (s_fontsLoaded) return;
    s_wBig.set(NOTES_FONT_BIG,     sizeof(NOTES_FONT_BIG));
    s_wTitle.set(NOTES_FONT_TITLE, sizeof(NOTES_FONT_TITLE));
    s_wBody.set(NOTES_FONT_BODY,   sizeof(NOTES_FONT_BODY));
    s_wMeta.set(NOTES_FONT_META,   sizeof(NOTES_FONT_META));
    s_fBig.loadFont(&s_wBig);
    s_fTitle.loadFont(&s_wTitle);
    s_fBody.loadFont(&s_wBody);
    s_fMeta.loadFont(&s_wMeta);
    s_fontsLoaded = true;
}

static void unloadFonts() {
    if (!s_fontsLoaded) return;
    s_fBig.unloadFont(); s_fTitle.unloadFont();
    s_fBody.unloadFont(); s_fMeta.unloadFont();
    s_fontsLoaded = false;
}

// ── Palette (RGB565, set once in runNotesUi from the mockup hex) ─────────────
static uint16_t C_PAPER, C_CARD, C_INK, C_MUTED, C_HAIR, C_ACCENT;
static uint16_t C_SEARCH, C_PREV, C_META, C_SHADOW, C_SAVED;

static void initColors() {
    C_PAPER  = G->color565(0xF7, 0xF5, 0xF0);
    C_CARD   = G->color565(0xFF, 0xFF, 0xFF);
    C_INK    = G->color565(0x23, 0x21, 0x1C);
    C_MUTED  = G->color565(0x9A, 0x96, 0x8C);
    C_HAIR   = G->color565(0xEC, 0xE9, 0xE2);
    C_ACCENT = G->color565(0xF4, 0xB7, 0x40);
    C_SEARCH = G->color565(0xEF, 0xEB, 0xE3);
    C_PREV   = G->color565(0x8A, 0x86, 0x7C);
    C_META   = G->color565(0xB4, 0xB0, 0xA6);
    C_SHADOW = G->color565(0xE4, 0xE0, 0xD7);   // soft drop shadow on paper
    C_SAVED  = G->color565(0x4C, 0xAF, 0x50);   // save-confirmation green
}

// ── Real notes (SD-backed) ────────────────────────────────────────────────────
// One file per note: /notes/NNN.txt — line 1 = title, remaining lines = body.
// No SD → falls back to an in-RAM starter set (session-only, not persisted).
struct NoteRec {
    String              title;
    std::vector<String> body;    // always >=1 element while a note is open
    String              path;    // "/notes/NNN.txt"; empty = never saved yet
    bool                dirty = false;
};
static std::vector<NoteRec> s_notes;   // loaded on entry, freed on exit (rule 5c)

static bool parseIndex(const String& fname, int& idxOut) {
    int dot = fname.lastIndexOf('.');
    if (dot <= 0) return false;
    String num = fname.substring(0, dot);
    for (size_t i = 0; i < num.length(); i++) if (!isDigit(num[i])) return false;
    idxOut = num.toInt();
    return true;
}

static bool loadNoteFile(const String& path, NoteRec& out) {
    File f = SD.open(path.c_str(), FILE_READ);
    if (!f) return false;
    out.path = path;
    out.dirty = false;
    bool first = true;
    while (f.available()) {
        String line = f.readStringUntil('\n');
        if (line.endsWith("\r")) line.remove(line.length() - 1);
        if (first) { out.title = line; first = false; }
        else        out.body.push_back(line);
    }
    f.close();
    if (out.body.empty()) out.body.push_back("");
    if (out.title.length() == 0) out.title = "Untitled";
    return true;
}

// Assigns the next free sequential filename if unsaved, writes title+body.
static bool saveNote(NoteRec& n) {
    if (!sdCardManager.canAccessSD()) return false;
    if (n.title.length() == 0) n.title = "Untitled";
    if (n.path.length() == 0) {
        sdCardManager.ensureDir(SD_DIR_NOTES);
        char path[32];
        int idx = 1;
        do { snprintf(path, sizeof(path), "%s/%03d.txt", SD_DIR_NOTES, idx++); } while (SD.exists(path));
        n.path = path;
    }
    File f = SD.open(n.path.c_str(), FILE_WRITE);
    if (!f) return false;
    f.println(n.title);
    for (auto& line : n.body) f.println(line);
    f.close();
    n.dirty = false;
    return true;
}

struct NoteSeed { const char* title; std::initializer_list<const char*> lines; };
static const NoteSeed kSeeds[] = {
    {"Lemon cake",   {"Preheat oven to 180C.", "Cream 200g butter with 200g sugar.",
                       "Add 3 eggs, one at a time.", "Fold in 200g flour + zest of 2 lemons.",
                       "Bake 35-40 min."}},
    {"Weekend trip", {"Charger + cable", "Passport", "Sunscreen", "The blue book", "Swim stuff"}},
    {"Groceries",    {"Milk", "Eggs", "Coffee beans", "Bananas", "Olive oil", "Sourdough loaf"}},
    {"Home WiFi",    {"Network: Skyfall_5G", "Password is on the fridge magnet by the door.",
                       "Guest network: Skyfall_guest"}},
};

// Writes the starter set as REAL files — used on first run so a PC-browsed
// card looks lived-in immediately (plan: "ship 4-6 believable decoy notes").
static void seedStarterFiles() {
    for (auto& s : kSeeds) {
        NoteRec n; n.title = s.title;
        for (auto* l : s.lines) n.body.push_back(l);
        saveNote(n);
    }
}

static void scanNotesDir(std::vector<std::pair<int, String>>& entries) {
    entries.clear();
    File dir = SD.open(SD_DIR_NOTES);
    if (!dir || !dir.isDirectory()) { if (dir) dir.close(); return; }
    File f = dir.openNextFile();
    while (f) {
        if (!f.isDirectory()) {
            String base(f.name());
            if (base.endsWith(".txt")) {
                int idx;
                if (parseIndex(base, idx))
                    entries.push_back({idx, String(SD_DIR_NOTES) + "/" + base});
            }
        }
        f = dir.openNextFile();
    }
    dir.close();
}

static void loadNotesFromSD() {
    s_notes.clear();

    if (!sdCardManager.canAccessSD()) {
        // No SD — small in-RAM starter set; edits are session-only (not saved).
        for (auto& s : kSeeds) {
            NoteRec n; n.title = s.title;
            for (auto* l : s.lines) n.body.push_back(l);
            s_notes.push_back(n);
        }
        return;
    }

    sdCardManager.ensureDir(SD_DIR_NOTES);
    std::vector<std::pair<int, String>> entries;
    scanNotesDir(entries);
    if (entries.empty()) {
        seedStarterFiles();
        scanNotesDir(entries);
    }

    // newest-first
    std::sort(entries.begin(), entries.end(),
              [](const std::pair<int, String>& a, const std::pair<int, String>& b) { return a.first > b.first; });

    for (auto& e : entries) {
        NoteRec n;
        if (loadNoteFile(e.second, n)) s_notes.push_back(n);
    }
}

static String notePreview(const NoteRec& n) {
    for (auto& line : n.body) { String t = line; t.trim(); if (t.length()) return t; }
    return String("(empty)");
}

// ── Layout (real px @ 320x240) ───────────────────────────────────────────────
#define SB_H        18                 // fake status bar height
#define APPBAR_Y    (SB_H + 8)          // Notes title — clearance under the status-bar clock
#define SEARCH_Y    54                  // gap below the 20px title so it isn't crowded
#define SEARCH_H    26
#define LIST_TOP    (SEARCH_Y + SEARCH_H + 8)   // scroll region top (= 86)
#define CARD_X      10
#define CARD_W      (SCREEN_WIDTH - 20)
#define CARD_H      58                  // tall enough for title + preview + meta
#define CARD_GAP    6
#define LABEL_H     18
#define FAB_R       22
#define FAB_CX      (SCREEN_WIDTH - 14 - FAB_R)
#define FAB_CY      (SCREEN_HEIGHT - 14 - FAB_R)

enum { VIEW_LIST, VIEW_DETAIL };

// unscrolled top offset (from LIST_TOP) of card i, and total content height —
// flat single-section list (no pinned/tint — that was demo-only decoration).
static int cardTop(int i) { return LABEL_H + i * (CARD_H + CARD_GAP); }
static int contentHeight() {
    int n = (int)s_notes.size();
    return n > 0 ? cardTop(n - 1) + CARD_H + CARD_GAP : LABEL_H;
}
static int maxScroll() {
    int h = contentHeight() - (SCREEN_HEIGHT - LIST_TOP);
    return h > 0 ? h : 0;
}

// truncate a string with ".." so it fits maxW at the current font
static void drawClipped(const char* s, int x, int y, int maxW, uint16_t color) {
    G->setTextColor(color);
    if (G->textWidth(s) <= maxW) { G->drawString(s, x, y); return; }
    String str(s);
    while (str.length() && G->textWidth((str + "..").c_str()) > maxW) str.remove(str.length() - 1);
    G->drawString((str + "..").c_str(), x, y);
}

// ── Status chrome (fake clock + signal + battery) ────────────────────────────
static void drawStatusBar() {
    G->fillRect(0, 0, SCREEN_WIDTH, SB_H, C_PAPER);
    G->setTextDatum(textdatum_t::middle_left);
    G->setFont(&s_fMeta);                 // small status clock (mockup ~10px), not the 15px title font
    G->setTextColor(C_INK);
    G->drawString("14:32", 12, SB_H / 2);
    G->setTextDatum(textdatum_t::top_left);

    // signal bars (right)
    int bx = SCREEN_WIDTH - 58, by = SB_H - 4;
    for (int i = 0; i < 4; i++) {
        int h = 3 + i * 3;
        G->fillRect(bx + i * 5, by - h, 3, h, C_INK);
    }
    // battery
    int btx = SCREEN_WIDTH - 30, bty = 3, btw = 22, bth = 11;
    G->drawRoundRect(btx, bty, btw, bth, 2, C_INK);
    G->fillRect(btx + btw, bty + 3, 2, bth - 6, C_INK);           // nub
    G->fillRect(btx + 2, bty + 2, (btw - 4) * 72 / 100, bth - 4, C_INK);  // 72% fill
}

// ── LIST view ────────────────────────────────────────────────────────────────
static void drawCard(int i, int screenY, bool selected) {
    const NoteRec& n = s_notes[i];
    G->fillSmoothRoundRect(CARD_X + 1, screenY + 2, CARD_W, CARD_H, 11, C_SHADOW);
    G->fillSmoothRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, C_CARD);
    G->drawRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, selected ? C_ACCENT : C_HAIR);

    int tx = CARD_X + 13;
    G->setFont(&s_fTitle);
    drawClipped(n.title.c_str(), tx, screenY + 9, CARD_X + CARD_W - 13 - tx, C_INK);
    G->setFont(&s_fMeta);
    drawClipped(notePreview(n).c_str(), tx, screenY + 31, CARD_W - 26, C_PREV);
    G->setTextColor(C_META);
    int lc = (int)n.body.size();
    char m[24]; snprintf(m, sizeof(m), "%d line%s", lc, lc == 1 ? "" : "s");
    G->drawString(m, tx, screenY + 43);
}

static void drawSectionLabel(const char* s, int screenY) {
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    G->drawString(s, CARD_X + 4, screenY + 2);
}

static void drawList(int scroll, int sel) {
    G->fillRect(0, SB_H, SCREEN_WIDTH, SCREEN_HEIGHT - SB_H, C_PAPER);

    // appbar
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fBig);
    G->setTextColor(C_INK);
    G->drawString("Notes", 14, APPBAR_Y);
    // avatar
    int avr = 12, avx = SCREEN_WIDTH - 14 - avr, avy = APPBAR_Y + 6;
    G->fillSmoothCircle(avx, avy, avr, C_ACCENT);
    G->setFont(&s_fTitle);
    G->setTextColor(C_CARD);
    G->setTextDatum(textdatum_t::middle_center);
    G->drawString("A", avx, avy - 1);
    G->setTextDatum(textdatum_t::top_left);

    // search pill (decorative)
    G->fillSmoothRoundRect(10, SEARCH_Y, SCREEN_WIDTH - 20, SEARCH_H, 9, C_SEARCH);
    int mcx = 26, mcy = SEARCH_Y + SEARCH_H / 2;   // magnifier
    G->drawCircle(mcx, mcy - 1, 4, C_MUTED);
    G->drawWideLine(mcx + 3, mcy + 2, mcx + 6, mcy + 5, 2, C_MUTED);
    G->setFont(&s_fBody);
    G->setTextColor(C_MUTED);
    G->drawString("Search", 40, SEARCH_Y + 5);

    // scroll region: section label + cards, clipped so partial cards don't
    // spill over the fixed header/status bar
    G->setClipRect(0, LIST_TOP, SCREEN_WIDTH, SCREEN_HEIGHT - LIST_TOP);
    int base = LIST_TOP - scroll;
    drawSectionLabel("Notes", base);
    int n = (int)s_notes.size();
    if (n == 0) {
        G->setFont(&s_fBody);
        G->setTextColor(C_MUTED);
        G->drawString("No notes yet - tap + to add one", CARD_X + 4, base + LABEL_H + 12);
    } else {
        for (int i = 0; i < n; i++) {
            int y = base + cardTop(i);
            if (y > SCREEN_HEIGHT || y + CARD_H < LIST_TOP) continue;   // fully offscreen
            drawCard(i, y, i == sel);
        }
    }
    G->clearClipRect();

    // FAB (drawn last, floats over the list)
    G->fillSmoothCircle(FAB_CX, FAB_CY, FAB_R, C_ACCENT);
    G->drawWideLine(FAB_CX - 9, FAB_CY, FAB_CX + 9, FAB_CY, 3, C_CARD);
    G->drawWideLine(FAB_CX, FAB_CY - 9, FAB_CX, FAB_CY + 9, 3, C_CARD);
}

// keep the selected card fully inside the scroll region
static int scrollToSel(int sel, int scroll) {
    int top = cardTop(sel);
    int bot = top + CARD_H;
    int viewH = SCREEN_HEIGHT - LIST_TOP;
    if (top - scroll < 0)            scroll = top;
    if (bot - scroll > viewH)        scroll = bot - viewH;
    if (scroll < 0) scroll = 0;
    if (scroll > maxScroll()) scroll = maxScroll();
    return scroll;
}

// which card is under a tap at screen-y (list view); -1 if none
static int cardAtY(int tapY, int scroll) {
    if (tapY < LIST_TOP) return -1;
    int base = LIST_TOP - scroll;
    int n = (int)s_notes.size();
    for (int i = 0; i < n; i++) {
        int y = base + cardTop(i);
        if (tapY >= y && tapY <= y + CARD_H) return i;
    }
    return -1;
}

// ── DETAIL view — a real cursor-addressable editor ───────────────────────────
// Cursor is a (line, col) pair: line 0 = title, line 1..N = body[line-1]. This
// unifies title/body editing — moving the cursor UP out of the body naturally
// lands in the title, no separate "titling mode" needed.
#define DOC_TOP   (SB_H + 34)   // below the back bar

static String* vline(NoteRec& n, int vidx) {
    if (vidx == 0) return &n.title;
    int bi = vidx - 1;
    if (bi >= 0 && bi < (int)n.body.size()) return &n.body[bi];
    return nullptr;
}
static int vlineCount(const NoteRec& n) { return 1 + (int)n.body.size(); }

// One word-wrapped visual row. colStart is the column into the ORIGINAL
// (unwrapped) source line where this row begins — this is what lets cursor
// placement and touch hit-testing map back to a real character position even
// though the text on screen has been split across multiple rows.
struct LayoutRow {
    int    vline;
    int    colStart;
    String text;
    int    y;         // doc-relative (scroll-independent) y
    bool   isTitle;
};

// Pure layout, no drawing — word-wraps title+body into rows with exact column
// offsets. Returns total doc-relative content height. Reused for measuring
// (docMaxScroll), cursor placement (ensureCursorVisible), touch hit-testing
// (moveCursorToTap), and rendering (drawDetail calls this once then draws the
// rows it collected, avoiding a second wrap pass just to draw).
static int layoutNote(const NoteRec& n, std::vector<LayoutRow>& rows) {
    rows.clear();
    int x = 26, maxW = SCREEN_WIDTH - x - 20;
    int y = 0;

    G->setFont(&s_fTitle);
    rows.push_back({0, 0, n.title, y, true});
    y += 24;
    y += 18;   // meta line (line count) — fixed, not part of cursor addressing

    G->setFont(&s_fBody);
    for (int bi = 0; bi < (int)n.body.size(); bi++) {
        const String& src = n.body[bi];
        int vl = bi + 1;
        if (src.length() == 0) { rows.push_back({vl, 0, "", y, false}); y += 20; continue; }
        int len = src.length();
        int rowStart = 0, lastSpace = -1, i = 0;
        while (i < len) {
            if (src[i] == ' ') lastSpace = i;
            String candidate = src.substring(rowStart, i + 1);
            if (G->textWidth(candidate.c_str()) > maxW && i > rowStart) {
                int breakAt = (lastSpace > rowStart) ? lastSpace : i;
                rows.push_back({vl, rowStart, src.substring(rowStart, breakAt), y, false});
                y += 20;
                rowStart = (lastSpace > rowStart) ? lastSpace + 1 : breakAt;
                lastSpace = -1;
                i = rowStart;
                continue;
            }
            i++;
        }
        rows.push_back({vl, rowStart, src.substring(rowStart, len), y, false});
        y += 20;
    }
    return y;
}

static void renderRows(const std::vector<LayoutRow>& rows, int scroll) {
    for (auto& r : rows) {
        if (r.text.length() == 0) continue;   // blank row — nothing to draw
        G->setFont(r.isTitle ? &s_fTitle : &s_fBody);
        int sy = DOC_TOP - scroll + r.y;
        if (r.isTitle) drawClipped(r.text.c_str(), 26, sy, SCREEN_WIDTH - 46, C_INK);
        else { G->setTextColor(C_INK); G->drawString(r.text, 26, sy); }
    }
}

static int docMaxScroll(const NoteRec& n) {
    std::vector<LayoutRow> rows;
    int h = layoutNote(n, rows) + 8;
    int viewH = SCREEN_HEIGHT - DOC_TOP;
    return h > viewH ? h - viewH : 0;
}

// Adjusts docScroll (in place) so the row containing (curLine,curCol) is visible.
static void ensureCursorVisible(const NoteRec& n, int curLine, int curCol, int& docScroll) {
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    int rowY = 0, rowH = 20;
    for (auto& r : rows) {
        if (r.vline == curLine && curCol >= r.colStart && curCol <= r.colStart + (int)r.text.length()) {
            rowY = r.y; rowH = r.isTitle ? 24 : 20; break;
        }
    }
    int viewH = SCREEN_HEIGHT - DOC_TOP;
    if (rowY - docScroll < 0)         docScroll = rowY;
    if (rowY + rowH - docScroll > viewH) docScroll = rowY + rowH - viewH;
    if (docScroll < 0) docScroll = 0;
    int dm = docMaxScroll(n);
    if (docScroll > dm) docScroll = dm;
}

// Maps a tap (screen x/y) to the nearest (line, col) — "touch a line" support.
static void moveCursorToTap(const NoteRec& n, int tapX, int tapY, int scroll, int& curLine, int& curCol) {
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    int localY = tapY - DOC_TOP + scroll;
    const LayoutRow* best = nullptr; int bestDist = 0x7fffffff;
    for (auto& r : rows) {
        int rh = r.isTitle ? 24 : 20;
        if (localY >= r.y && localY < r.y + rh) { best = &r; break; }
        int d = abs(localY - r.y);
        if (d < bestDist) { bestDist = d; best = &r; }
    }
    if (!best) return;
    curLine = best->vline;
    G->setFont(best->isTitle ? &s_fTitle : &s_fBody);
    int tx = tapX - 26;
    int col = (int)best->text.length();
    for (int ci = 0; ci <= (int)best->text.length(); ci++) {
        String prefix = best->text.substring(0, ci);
        if (G->textWidth(prefix.c_str()) >= tx) { col = ci; break; }
    }
    curCol = best->colStart + col;
}

static uint32_t s_saveNoticeMs = 0;   // "Saved"/"No SD" toast timer (save-icon tap)
static bool     s_saveNoticeOk = true;

static void drawDetail(const NoteRec& n, int scroll, int curLine, int curCol, bool cursorOn) {
    G->fillRect(0, SB_H, SCREEN_WIDTH, SCREEN_HEIGHT - SB_H, C_PAPER);

    // back bar
    int barY = SB_H, barH = 34;
    G->drawFastHLine(0, barY + barH - 1, SCREEN_WIDTH, C_HAIR);
    // chevron
    int cvx = 16, cvy = barY + barH / 2;
    G->drawWideLine(cvx + 5, cvy - 5, cvx, cvy, 2, C_ACCENT);
    G->drawWideLine(cvx, cvy, cvx + 5, cvy + 5, 2, C_ACCENT);
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fTitle);
    G->setTextColor(C_ACCENT);
    G->drawString("Notes", cvx + 12, barY + 8);

    // share icon (decorative, unchanged)
    int iy = cvy;
    int sx = SCREEN_WIDTH - 58;
    G->fillSmoothCircle(sx,     iy - 5, 2, C_ACCENT);
    G->fillSmoothCircle(sx - 8, iy,     2, C_ACCENT);
    G->fillSmoothCircle(sx,     iy + 5, 2, C_ACCENT);
    G->drawWideLine(sx - 7, iy - 1, sx - 1, iy - 4, 1, C_ACCENT);
    G->drawWideLine(sx - 7, iy + 1, sx - 1, iy + 4, 1, C_ACCENT);

    // SAVE button (was a decorative "download" icon — now functional: floppy glyph)
    int dx2 = SCREEN_WIDTH - 24;
    G->drawRoundRect(dx2 - 7, iy - 7, 14, 14, 2, C_ACCENT);
    G->fillRect(dx2 - 4, iy - 7, 8, 5, C_ACCENT);
    G->drawFastHLine(dx2 - 5, iy + 2, 10, C_ACCENT);

    if (millis() - s_saveNoticeMs < 1200) {
        G->setFont(&s_fMeta);
        G->setTextColor(s_saveNoticeOk ? C_SAVED : C_ACCENT);
        G->setTextDatum(textdatum_t::middle_right);
        G->drawString(s_saveNoticeOk ? "Saved" : "No SD", dx2 - 12, iy);
        G->setTextDatum(textdatum_t::top_left);
    }

    // doc body, clipped + scrolled
    G->setClipRect(0, DOC_TOP, SCREEN_WIDTH, SCREEN_HEIGHT - DOC_TOP);
    std::vector<LayoutRow> rows;
    layoutNote(n, rows);
    renderRows(rows, scroll);

    // meta line (line count) — fixed doc-relative y=24, under the title
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    int lc = (int)n.body.size();
    char m[24]; snprintf(m, sizeof(m), "%d line%s", lc, lc == 1 ? "" : "s");
    G->drawString(m, 26, DOC_TOP - scroll + 24);

    if (cursorOn) {
        for (auto& r : rows) {
            if (r.vline == curLine && curCol >= r.colStart && curCol <= r.colStart + (int)r.text.length()) {
                G->setFont(r.isTitle ? &s_fTitle : &s_fBody);
                String prefix = r.text.substring(0, curCol - r.colStart);
                int cx = 26 + G->textWidth(prefix.c_str());
                int cy = DOC_TOP - scroll + r.y;
                int ch = r.isTitle ? 18 : 16;
                G->fillRect(cx, cy, 2, ch, C_INK);
                break;
            }
        }
    }
    G->clearClipRect();
}

// tap on the back chevron/"Notes" region of the detail bar?
static bool tapBack(int x, int y) {
    return y >= SB_H && y <= SB_H + 34 && x <= 80;
}
// tap on the save-button icon?
static bool tapSave(int x, int y) {
    int dx2 = SCREEN_WIDTH - 24, iy = SB_H + 34 / 2;
    return x >= dx2 - 12 && x <= dx2 + 8 && y >= iy - 12 && y <= iy + 12;
}

// Compose a full frame into the canvas, then blit once (no flicker).
static void paintList(int scroll, int sel) { drawStatusBar(); drawList(scroll, sel); flushCanvas(); }
static void paintDetail(const NoteRec& n, int ds, int curLine, int curCol, bool cursorOn) {
    drawStatusBar(); drawDetail(n, ds, curLine, curCol, cursorOn); flushCanvas();
}

// ── Secret-passphrase rolling buffer ─────────────────────────────────────────
// Accumulates the last ucPhraseLen() printable keystrokes typed anywhere in the
// Notes UI and compares the tail against the stored hash after every keypress.
// No visual feedback — from the outside it looks like tapping random keys while
// reading a note. Reset at the top of runNotesUi() so each cover session starts
// clean (avoids leftovers from a previous partial entry).
static char     s_kbuf[33]    = {};
static int      s_kpos        = 0;
static uint32_t s_lastTapMs   = 0;   // double-tap state for screen-off wake

// ── Entry point ──────────────────────────────────────────────────────────────
void runNotesUi() {
    // Full-screen PSRAM back-buffer (150KB). Set G before any drawing so every
    // draw lands in the sprite; fall back to the panel if allocation fails.
    s_canvas.setPsram(true);
    s_canvas.setColorDepth(16);
    s_haveCanvas = s_canvas.createSprite(SCREEN_WIDTH, SCREEN_HEIGHT);
    G = s_haveCanvas ? (lgfx::LovyanGFX*)&s_canvas : (lgfx::LovyanGFX*)&tft;

    initColors();
    loadFonts();
    // Suppress the real T-REX status bar (ClockManager/battery redraws at y<30):
    // setBlocked no-ops DisplayManager output; we draw the whole screen ourselves,
    // exactly like the lock screen does while blocked. This is what the cover does.
    displayManager.setBlocked(true);

    // Fresh state each session.
    s_kbuf[0] = '\0'; s_kpos = 0; s_lastTapMs = 0; s_saveNoticeMs = 0; s_saveNoticeOk = true;

    loadNotesFromSD();

    int  view = VIEW_LIST, sel = 0, scroll = 0, cur = -1, docScroll = 0;
    int  curLine = 0, curCol = 0;   // cursor: 0=title, 1..N=body[line-1]
    bool cursorOn = true;
    uint32_t lastBlinkMs = millis();

    // Saves the open note if it has real content; otherwise drops a never-typed
    // placeholder (created by FAB-tap) so it doesn't leave a ghost list row.
    auto leaveDetail = [&]() {
        if (cur >= 0 && cur < (int)s_notes.size()) {
            NoteRec& n = s_notes[cur];
            if (n.dirty)                    saveNote(n);
            else if (n.path.length() == 0)  s_notes.erase(s_notes.begin() + cur);
        }
        view = VIEW_LIST; cur = -1;
        paintList(scroll, sel);
    };

    paintList(scroll, sel);

    TouchManager& tm = TouchManager::instance();

    bool s_wasDimmed = false;

    while (true) {
        if (LockScreenManager::getInstance().consumeJustUnlocked()) {
            displayManager.setBlocked(true);
            if (view == VIEW_LIST) paintList(scroll, sel);
            else if (cur >= 0)     paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
        }

        // While actually locked (LockScreenManager's OWN idle timer, independent of
        // undercover), its dormant screen draws directly to tft (setBlocked(false)
        // around itself) — bypassing our sprite compositing entirely. If we keep
        // painting/polling touch here too, its 1s duration-counter tick (real T-REX
        // status bar + "Locked: HH:MM:SS") leaks onto the panel and stays visible
        // until our next repaint. So: stand down completely and let it own the
        // screen, same as wguard/buddy do via isBlocked() — just keep pumping
        // getKeyboardInput() so PIN entry works and consumeJustUnlocked() fires the
        // moment it unlocks (handled above, next loop iteration).
        if (LockScreenManager::getInstance().isLocked()) {
            inputHandler.getKeyboardInput();
            vTaskDelay(pdMS_TO_TICKS(10));
            continue;
        }

        // Repaint after any dim→wake transition so the terminal never bleeds through.
        // The panel may have been partially redrawn (clock/status updates) while dim;
        // the sprite blit restores the cover atomically.
        {
            bool dimmed = PowerSaveManager::getInstance().isDimmed();
            if (s_wasDimmed && !dimmed) {
                displayManager.setBlocked(true);
                if (view == VIEW_LIST) paintList(scroll, sel);
                else if (cur >= 0)     paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
            s_wasDimmed = dimmed;
        }

        // Cursor blink while a note is open for editing — repaints every 500ms so
        // the caret visibly blinks even with no new input.
        if (view == VIEW_DETAIL && cur >= 0 && cur < (int)s_notes.size()) {
            uint32_t now = millis();
            if (now - lastBlinkMs >= 500) {
                lastBlinkMs = now;
                cursorOn = !cursorOn;
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
        }

        // ── touch ──
        TouchEvent te = tm.poll();
        if (te.type != TouchEvent::NONE) {
            inputHandler.updateActivity();
            // Power-save wake lives HERE — main.ino's loop is blocked while we run.
            PowerSaveManager& psm = PowerSaveManager::getInstance();
            if (!psm.isManualOff()) {
                if (psm.isScreenOff()) {
                    // Fully off: double-tap (two TAPs within 500 ms) to wake.
                    if (te.type == TouchEvent::TAP) {
                        uint32_t now = millis();
                        if (s_lastTapMs && (now - s_lastTapMs) < 500) {
                            psm.updateActivity(); s_lastTapMs = 0;
                        } else {
                            s_lastTapMs = now;
                        }
                    }
                } else {
                    // Half-dimmed: single touch wakes.
                    psm.updateActivity(); s_lastTapMs = 0;
                }
            }
        }

        if (view == VIEW_LIST) {
            if (te.type == TouchEvent::TAP) {
                int dx = te.x - FAB_CX, dy = te.y - FAB_CY;
                if (dx * dx + dy * dy <= (FAB_R + 4) * (FAB_R + 4)) {
                    s_notes.insert(s_notes.begin(), NoteRec());
                    cur = 0; sel = 0; docScroll = 0; curLine = 0; curCol = 0; cursorOn = true;
                    view = VIEW_DETAIL; paintDetail(s_notes[cur], 0, curLine, curCol, cursorOn);
                } else {
                    int hit = cardAtY(te.y, scroll);
                    if (hit >= 0) {
                        cur = hit; sel = hit; cursorOn = true;
                        NoteRec& nn = s_notes[cur];
                        curLine = vlineCount(nn) - 1;
                        String* ls = vline(nn, curLine);
                        curCol = ls ? (int)ls->length() : 0;
                        docScroll = docMaxScroll(nn);   // open at the end — continue typing
                        view = VIEW_DETAIL; paintDetail(nn, docScroll, curLine, curCol, cursorOn);
                    }
                }
            } else if (te.type == TouchEvent::DRAG_MOVE) {
                scroll -= te.dy;
                if (scroll < 0) scroll = 0;
                if (scroll > maxScroll()) scroll = maxScroll();
                paintList(scroll, sel);
            }
        } else { // VIEW_DETAIL
            if (te.type == TouchEvent::TAP && cur >= 0 && tapSave(te.x, te.y)) {
                if (s_notes[cur].dirty) {
                    s_saveNoticeOk = saveNote(s_notes[cur]);
                    s_saveNoticeMs = millis();
                } else if (s_notes[cur].path.length() > 0) {
                    s_saveNoticeOk = true;   // already on disk, nothing new to write
                    s_saveNoticeMs = millis();
                }
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            } else if (te.type == TouchEvent::TAP && tapBack(te.x, te.y)) {
                leaveDetail();
            } else if (te.type == TouchEvent::TAP && cur >= 0) {
                // Touch a line — cursor jumps there ("fix a word" support).
                moveCursorToTap(s_notes[cur], te.x, te.y, docScroll, curLine, curCol);
                ensureCursorVisible(s_notes[cur], curLine, curCol, docScroll);
                cursorOn = true; lastBlinkMs = millis();
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            } else if (te.type == TouchEvent::DRAG_MOVE && cur >= 0) {
                docScroll -= te.dy;
                int dm = docMaxScroll(s_notes[cur]);
                if (docScroll < 0) docScroll = 0;
                if (docScroll > dm) docScroll = dm;
                paintDetail(s_notes[cur], docScroll, curLine, curCol, cursorOn);
            }
        }

        // ── trackball ──
        // 300ms throttle — raw events fire far faster than deliberate movement.
        // List:   UP/DOWN = navigate cards · CLICK = open note
        // Detail: UP/DOWN/LEFT/RIGHT = move the cursor (LEFT/RIGHT wrap across
        //         lines; UP out of body line 0 lands in the title) · CLICK = back
        //         to list (saves) — the only back-trigger now that LEFT moves
        //         the cursor.
        TrackballEvent tb = inputHandler.getTrackballEvent();
        static uint32_t s_lastTbMs = 0;
        if (tb != TBALL_NONE) {
            uint32_t now = millis();
            if (now - s_lastTbMs >= 300) {
                s_lastTbMs = now;
                if (view == VIEW_LIST) {
                    int n = (int)s_notes.size();
                    if (tb == TBALL_DOWN && sel < n - 1) {
                        sel++; scroll = scrollToSel(sel, scroll);
                        paintList(scroll, sel);
                    } else if (tb == TBALL_UP && sel > 0) {
                        sel--; scroll = scrollToSel(sel, scroll);
                        paintList(scroll, sel);
                    } else if (tb == TBALL_CLICK && n > 0) {
                        cur = sel; cursorOn = true;
                        NoteRec& nn = s_notes[cur];
                        curLine = vlineCount(nn) - 1;
                        String* ls = vline(nn, curLine);
                        curCol = ls ? (int)ls->length() : 0;
                        docScroll = docMaxScroll(nn);
                        view = VIEW_DETAIL; paintDetail(nn, docScroll, curLine, curCol, cursorOn);
                    }
                } else if (cur >= 0) { // VIEW_DETAIL
                    if (tb == TBALL_CLICK) {
                        leaveDetail();
                    } else {
                        NoteRec& n = s_notes[cur];
                        int maxLine = vlineCount(n) - 1;
                        bool moved = false;
                        if (tb == TBALL_UP && curLine > 0) {
                            curLine--;
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol > len) curCol = len;
                            moved = true;
                        } else if (tb == TBALL_DOWN && curLine < maxLine) {
                            curLine++;
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol > len) curCol = len;
                            moved = true;
                        } else if (tb == TBALL_LEFT) {
                            if (curCol > 0) { curCol--; moved = true; }
                            else if (curLine > 0) {
                                curLine--;
                                String* ls = vline(n, curLine);
                                curCol = ls ? (int)ls->length() : 0;
                                moved = true;
                            }
                        } else if (tb == TBALL_RIGHT) {
                            String* ls = vline(n, curLine);
                            int len = ls ? (int)ls->length() : 0;
                            if (curCol < len) { curCol++; moved = true; }
                            else if (curLine < maxLine) { curLine++; curCol = 0; moved = true; }
                        }
                        if (moved) {
                            ensureCursorVisible(n, curLine, curCol, docScroll);
                            cursorOn = true; lastBlinkMs = millis();
                            paintDetail(n, docScroll, curLine, curCol, cursorOn);
                        }
                    }
                }
            }
        }

        // ── keyboard ──
        char k = inputHandler.getKeyboardInput();

        // Secret-passphrase check: accumulate printable keys into a sliding window
        // of ucPhraseLen() chars and compare the hash after every keypress. No
        // feedback — match silently exits the cover exactly like typing a memo.
        // OPSEC: on match we deliberately do NOT save the currently-open note —
        // the phrase characters were just typed into its title/body in earlier
        // loop iterations (before we could know a match was imminent), so saving
        // now would write the passphrase itself into a plaintext .txt on the SD
        // card. Skipping the save keeps the hash the ONLY place it ever exists.
        if (k >= 0x20 && k < 0x7F && ucHasPassphrase()) {
            int plen = ucPhraseLen();
            if (plen > 0 && plen <= 32) {
                if (s_kpos < plen) { s_kbuf[s_kpos++] = k; }
                else { memmove(s_kbuf, s_kbuf + 1, plen - 1); s_kbuf[plen - 1] = k; }
                s_kbuf[s_kpos < plen ? s_kpos : plen] = '\0';
                if (s_kpos >= plen && ucCheckPhrase(s_kbuf)) break;
            }
        }

        if ((k == 'q' || k == 'Q') && !ucHasPassphrase()) {
            // Fallback exit (only reachable with no passphrase configured — no
            // secret to protect here, so saving the open note is safe.
            if (cur >= 0 && cur < (int)s_notes.size() && s_notes[cur].dirty) saveNote(s_notes[cur]);
            break;
        }

        // Typing — inserts/deletes at (curLine, curCol), not just at the end, so
        // any line (including the title) can be edited after moving the cursor
        // there via touch or trackball.
        if (view == VIEW_DETAIL && cur >= 0 && cur < (int)s_notes.size()) {
            NoteRec& n = s_notes[cur];
            bool changed = false;
            if (k == '\x08' || k == '\x7F') {                        // backspace
                String* ls = vline(n, curLine);
                if (ls) {
                    if (curCol > 0) {
                        ls->remove(curCol - 1, 1);
                        curCol--; changed = true;
                    } else if (curLine > 0) {
                        // merge this line into the end of the previous one
                        String tail = *ls;                     // copy before any vector mutation
                        int prevLine = curLine - 1;
                        String* prev = vline(n, prevLine);
                        if (prev) {
                            int mergeCol = prev->length();
                            *prev += tail;
                            int bi = curLine - 1;
                            if (bi >= 0 && bi < (int)n.body.size()) n.body.erase(n.body.begin() + bi);
                            curLine = prevLine; curCol = mergeCol;
                            changed = true;
                        }
                    }
                }
            } else if (k == '\r' || k == '\n') {                     // enter — split at cursor
                String* ls = vline(n, curLine);
                if (ls) {
                    String tail = ls->substring(curCol);
                    *ls = ls->substring(0, curCol);
                    if (curLine == 0) {
                        n.body.insert(n.body.begin(), tail);
                        curLine = 1; curCol = 0;
                    } else {
                        int bi = curLine - 1;
                        n.body.insert(n.body.begin() + bi + 1, tail);
                        curLine++; curCol = 0;
                    }
                    changed = true;
                }
            } else if (k >= 0x20 && k < 0x7F) {                      // printable — insert at cursor
                String* ls = vline(n, curLine);
                int cap = (curLine == 0) ? 40 : 200;
                if (ls && (int)ls->length() < cap) {
                    *ls = ls->substring(0, curCol) + String(k) + ls->substring(curCol);
                    curCol++; changed = true;
                }
            }
            if (changed) {
                n.dirty = true;
                ensureCursorVisible(n, curLine, curCol, docScroll);
                cursorOn = true; lastBlinkMs = millis();
                paintDetail(n, docScroll, curLine, curCol, cursorOn);
            }
        }
    }

    // restore CLI
    s_notes.clear(); s_notes.shrink_to_fit();
    unloadFonts();
    if (s_haveCanvas) { s_canvas.deleteSprite(); s_haveCanvas = false; }
    G = &tft;
    tft.setFont(&fonts::Font0);
    tft.setTextDatum(textdatum_t::top_left);
    displayManager.setBlocked(false);
    displayManager.clearScreen();
    displayManager.setCursor(10, outputY);
    displayManager.printCommandScreen();
    // If we were panic-hidden mid-command, the command's static UI was blanked by
    // the cover. Raise the unlock-style repaint signal so it fully redraws on its
    // next loop (every consumeJustUnlocked-aware command: ws, sw, wguard, ...).
    LockScreenManager::getInstance().signalRedraw();
}
