// T-REX — offensive security firmware for LilyGo T-DECK
// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Abdallah Natsheh
//
// Notes cover UI — Phase 2 test. Visual spec + palette from the approved mockup
// (trex-undercover-notes.html); mockup is drawn 2x, real px = mockup / 2.
// Draws directly to the global LGFX (like buddy/editor). Text uses anti-aliased
// Noto Sans (Android's font family) baked to VLW smooth fonts — notes_fonts.h,
// generated by convert_font.py — for a modern, non-terminal look.

#include "notes_ui.h"
#include "display_manager.h"
#include "input_handling.h"
#include "touch_manager.h"
#include "lockscreen_manager.h"
#include "notes_fonts.h"      // baked Noto Sans VLW smooth fonts (convert_font.py)
#include <Arduino.h>

extern LGFX           tft;
extern DisplayManager displayManager;
extern InputHandling  inputHandler;

// ── Double buffering ────────────────────────────────────────────────────────
// Every touch/drag event repaints the whole view; drawing that straight to the
// panel shows the clear→redraw as flicker. So all draw calls go through `G`,
// which points at a full-screen PSRAM sprite; each frame is composed off-screen
// then blitted in one pushSprite (same pattern as csidetect's radar). If the
// PSRAM sprite can't be allocated, G falls back to the panel (flickers, but
// still works).
static LGFX_Sprite      s_canvas(&tft);
static lgfx::LovyanGFX* G = &tft;
static bool             s_haveCanvas = false;

static void flushCanvas() {
    if (s_haveCanvas) s_canvas.pushSprite(&tft, 0, 0);
}

// ── Anti-aliased smooth fonts (Noto Sans, baked to VLW) ─────────────────────
// Held as persistent VLWfont objects loaded once per session — switching with
// setFont() then costs nothing (no re-parse). PointerWrapper reads the glyph
// data straight from the flash array via memcpy_P. F_BIG=app title, F_TITLE=
// card/detail titles, F_BODY=preview/body, F_META=meta/section labels.
static lgfx::VLWfont        s_fBig, s_fTitle, s_fBody, s_fMeta;
static lgfx::PointerWrapper s_wBig, s_wTitle, s_wBody, s_wMeta;
static bool                 s_fontsLoaded = false;

static void loadFonts() {
    if (s_fontsLoaded) return;
    s_wBig.set(NOTES_FONT_BIG,     sizeof(NOTES_FONT_BIG));
    s_wTitle.set(NOTES_FONT_TITLE, sizeof(NOTES_FONT_TITLE));
    s_wBody.set(NOTES_FONT_BODY,   sizeof(NOTES_FONT_BODY));
    s_wMeta.set(NOTES_FONT_META,   sizeof(NOTES_FONT_META));
    s_fBig.loadFont(&s_wBig);
    s_fTitle.loadFont(&s_wTitle);
    s_fBody.loadFont(&s_wBody);
    s_fMeta.loadFont(&s_wMeta);
    s_fontsLoaded = true;
}

static void unloadFonts() {
    if (!s_fontsLoaded) return;
    s_fBig.unloadFont(); s_fTitle.unloadFont();
    s_fBody.unloadFont(); s_fMeta.unloadFont();
    s_fontsLoaded = false;
}

// ── Palette (RGB565, set once in runNotesUi from the mockup hex) ─────────────
static uint16_t C_PAPER, C_CARD, C_INK, C_MUTED, C_HAIR, C_ACCENT;
static uint16_t C_TBLUE, C_TGREEN, C_TPINK, C_SEARCH, C_PREV, C_META, C_AVEDGE, C_SHADOW;
static uint16_t C_BDBLUE, C_BDGREEN, C_BDPINK;

static void initColors() {
    C_PAPER  = G->color565(0xF7, 0xF5, 0xF0);
    C_CARD   = G->color565(0xFF, 0xFF, 0xFF);
    C_INK    = G->color565(0x23, 0x21, 0x1C);
    C_MUTED  = G->color565(0x9A, 0x96, 0x8C);
    C_HAIR   = G->color565(0xEC, 0xE9, 0xE2);
    C_ACCENT = G->color565(0xF4, 0xB7, 0x40);
    C_TBLUE  = G->color565(0xEA, 0xF1, 0xF7);
    C_TGREEN = G->color565(0xEB, 0xF3, 0xEC);
    C_TPINK  = G->color565(0xF8, 0xEE, 0xF1);
    C_BDBLUE = G->color565(0xDF, 0xEA, 0xF2);   // tinted-card borders (mockup)
    C_BDGREEN= G->color565(0xDF, 0xED, 0xE0);
    C_BDPINK = G->color565(0xF1, 0xE2, 0xE6);
    C_SEARCH = G->color565(0xEF, 0xEB, 0xE3);
    C_PREV   = G->color565(0x8A, 0x86, 0x7C);
    C_META   = G->color565(0xB4, 0xB0, 0xA6);
    C_AVEDGE = G->color565(0xE8, 0x9A, 0x2C);
    C_SHADOW = G->color565(0xE4, 0xE0, 0xD7);   // soft drop shadow on paper
}

// ── Sample notes (hardcoded for the test — real /notes/*.txt comes later) ────
struct BodyLine { const char* text; bool check; bool done; };
struct Note {
    const char* title;
    bool        pinned;
    uint8_t     tint;          // 0 = white · 1 = blue · 2 = green · 3 = pink
    const char* preview;
    const char* meta;
    const BodyLine* body;
    uint8_t     bodyCount;
};

static const BodyLine bodyWifi[] = {
    {"Network: Skyfall_5G", false, false},
    {"Password is on the fridge magnet by the door.", false, false},
    {"Guest network: Skyfall_guest", false, false},
};
static const BodyLine bodyGro[] = {
    {"Milk", true, true}, {"Eggs", true, true}, {"Coffee beans", true, false},
    {"Bananas", true, false}, {"Olive oil", true, false}, {"Sourdough loaf", true, false},
};
static const BodyLine bodyTrip[] = {
    {"Charger + cable", true, true}, {"Passport", true, false}, {"Sunscreen", true, false},
    {"The blue book", true, false}, {"Swim stuff", true, false},
};
static const BodyLine bodyCake[] = {
    {"Preheat oven to 180C.", false, false},
    {"Cream 200g butter with 200g sugar.", false, false},
    {"Add 3 eggs, one at a time.", false, false},
    {"Fold in 200g flour + zest of 2 lemons.", false, false},
    {"Bake 35-40 min.", false, false},
};
static const BodyLine bodyPlumb[] = {
    {"Tuesday after 3pm.", false, false},
    {"Slow drain under the kitchen sink - getting worse.", false, false},
    {"Ask about the dripping bath tap too.", false, false},
};
static const BodyLine bodyMovies[] = {
    {"Past Lives", true, false}, {"Dune: Part Two", true, true},
    {"Perfect Days", true, false}, {"The Holdovers", true, false},
};

static const Note NOTES[] = {
    {"Home WiFi",     true,  0,       "Network: Skyfall_5G  -  pass on the fridge magnet",       "Mon",   bodyWifi,  3},
    {"Groceries",     false, 2,       "Milk, eggs, coffee, bananas, olive oil, sourdough",       "Today", bodyGro,   6},
    {"Weekend trip",  false, 0,       "Charger, passport, sunscreen, the blue book, swim stuff", "Today", bodyTrip,  5},
    {"Lemon cake",    false, 1,       "Preheat 180C. Cream butter & sugar, then 3 eggs...",      "Sat",   bodyCake,  5},
    {"Call plumber",  false, 0,       "Tue after 3pm - slow drain under the kitchen sink",       "Fri",   bodyPlumb, 3},
    {"Movies to watch",false,3,       "Past Lives, Dune Part Two, Perfect Days, The Holdovers",  "Thu",   bodyMovies,4},
};
static const int NOTE_COUNT = sizeof(NOTES) / sizeof(NOTES[0]);

// ── Layout (real px @ 320x240) ───────────────────────────────────────────────
#define SB_H        18                 // fake status bar height
#define APPBAR_Y    (SB_H + 4)
#define SEARCH_Y    46
#define SEARCH_H    26
#define LIST_TOP    (SEARCH_Y + SEARCH_H + 8)   // scroll region top
#define CARD_X      10
#define CARD_W      (SCREEN_WIDTH - 20)
#define CARD_H      54
#define CARD_GAP    6
#define LABEL_H     18
#define FAB_R       22
#define FAB_CX      (SCREEN_WIDTH - 14 - FAB_R)
#define FAB_CY      (SCREEN_HEIGHT - 14 - FAB_R)

enum { VIEW_LIST, VIEW_DETAIL };

// unscrolled top offset (from LIST_TOP) of card i, and total content height
static int cardTop(int i) {
    // [Pinned label][card0][Recent label][card1..]
    if (i == 0) return LABEL_H;
    return LABEL_H + (CARD_H + CARD_GAP) + LABEL_H + (i - 1) * (CARD_H + CARD_GAP);
}
static int contentHeight() {
    return cardTop(NOTE_COUNT - 1) + CARD_H + CARD_GAP;
}
static int maxScroll() {
    int h = contentHeight() - (SCREEN_HEIGHT - LIST_TOP);
    return h > 0 ? h : 0;
}

static uint16_t cardTint(uint8_t t) {
    switch (t) { case 1: return C_TBLUE; case 2: return C_TGREEN; case 3: return C_TPINK; default: return C_CARD; }
}
static uint16_t cardBorder(uint8_t t) {
    switch (t) { case 1: return C_BDBLUE; case 2: return C_BDGREEN; case 3: return C_BDPINK; default: return C_HAIR; }
}

// truncate a string with ".." so it fits maxW at the current font
static void drawClipped(const char* s, int x, int y, int maxW, uint16_t color) {
    G->setTextColor(color);
    if (G->textWidth(s) <= maxW) { G->drawString(s, x, y); return; }
    String str(s);
    while (str.length() && G->textWidth((str + "..").c_str()) > maxW) str.remove(str.length() - 1);
    G->drawString((str + "..").c_str(), x, y);
}

// ── Status chrome (fake clock + signal + battery) ────────────────────────────
static void drawStatusBar() {
    G->fillRect(0, 0, SCREEN_WIDTH, SB_H, C_PAPER);
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fTitle);
    G->setTextColor(C_INK);
    G->drawString("14:32", 12, 2);

    // signal bars (right)
    int bx = SCREEN_WIDTH - 58, by = SB_H - 4;
    for (int i = 0; i < 4; i++) {
        int h = 3 + i * 3;
        G->fillRect(bx + i * 5, by - h, 3, h, C_INK);
    }
    // battery
    int btx = SCREEN_WIDTH - 30, bty = 3, btw = 22, bth = 11;
    G->drawRoundRect(btx, bty, btw, bth, 2, C_INK);
    G->fillRect(btx + btw, bty + 3, 2, bth - 6, C_INK);           // nub
    G->fillRect(btx + 2, bty + 2, (btw - 4) * 72 / 100, bth - 4, C_INK);  // 72% fill
}

// ── LIST view ────────────────────────────────────────────────────────────────
static void drawCard(int i, int screenY, bool selected) {
    const Note& n = NOTES[i];
    uint16_t bg = cardTint(n.tint);
    // soft drop shadow (2px below/right, one shade darker than paper) → depth
    G->fillSmoothRoundRect(CARD_X + 1, screenY + 2, CARD_W, CARD_H, 11, C_SHADOW);
    G->fillSmoothRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, bg);
    // hairline border (accent when trackball-selected, else a tint-matched hair)
    G->drawRoundRect(CARD_X, screenY, CARD_W, CARD_H, 11, selected ? C_ACCENT : cardBorder(n.tint));

    int tx = CARD_X + 13;
    // title (+ pinned dot)
    G->setFont(&s_fTitle);
    int titleX = tx;
    if (n.pinned) {
        G->fillSmoothCircle(tx + 3, screenY + 16, 3, C_ACCENT);
        titleX = tx + 13;
    }
    drawClipped(n.title, titleX, screenY + 8, CARD_X + CARD_W - 13 - titleX, C_INK);
    // preview (smaller, secondary)
    G->setFont(&s_fMeta);
    drawClipped(n.preview, tx, screenY + 28, CARD_W - 26, C_PREV);
    // meta
    G->setFont(&s_fMeta);
    G->setTextColor(C_META);
    G->drawString(n.meta, tx, screenY + 41);
}

static void drawSectionLabel(const char* s, int screenY) {
    G->setFont(&s_fMeta);
    G->setTextColor(C_MUTED);
    G->drawString(s, CARD_X + 4, screenY + 2);
}

static void drawList(int scroll, int sel) {
    G->fillRect(0, SB_H, SCREEN_WIDTH, SCREEN_HEIGHT - SB_H, C_PAPER);

    // appbar
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fBig);
    G->setTextColor(C_INK);
    G->drawString("Notes", 14, APPBAR_Y);
    // avatar
    int avr = 12, avx = SCREEN_WIDTH - 14 - avr, avy = APPBAR_Y + 6;
    G->fillSmoothCircle(avx, avy, avr, C_ACCENT);
    G->setFont(&s_fTitle);
    G->setTextColor(C_CARD);
    G->setTextDatum(textdatum_t::middle_center);
    G->drawString("A", avx, avy - 1);
    G->setTextDatum(textdatum_t::top_left);

    // search pill
    G->fillSmoothRoundRect(10, SEARCH_Y, SCREEN_WIDTH - 20, SEARCH_H, 9, C_SEARCH);
    int mcx = 26, mcy = SEARCH_Y + SEARCH_H / 2;   // magnifier
    G->drawCircle(mcx, mcy - 1, 4, C_MUTED);
    G->drawWideLine(mcx + 3, mcy + 2, mcx + 6, mcy + 5, 2, C_MUTED);
    G->setFont(&s_fBody);
    G->setTextColor(C_MUTED);
    G->drawString("Search", 40, SEARCH_Y + 5);

    // scroll region: section labels + cards, clipped so partial cards don't
    // spill over the fixed header/status bar
    G->setClipRect(0, LIST_TOP, SCREEN_WIDTH, SCREEN_HEIGHT - LIST_TOP);
    int base = LIST_TOP - scroll;
    drawSectionLabel("Pinned", base);
    drawSectionLabel("Recent", base + LABEL_H + CARD_H + CARD_GAP);
    for (int i = 0; i < NOTE_COUNT; i++) {
        int y = base + cardTop(i);
        if (y > SCREEN_HEIGHT || y + CARD_H < LIST_TOP) continue;   // fully offscreen
        drawCard(i, y, i == sel);
    }
    G->clearClipRect();

    // FAB (drawn last, floats over the list)
    G->fillSmoothCircle(FAB_CX, FAB_CY, FAB_R, C_ACCENT);
    G->drawWideLine(FAB_CX - 9, FAB_CY, FAB_CX + 9, FAB_CY, 3, C_CARD);
    G->drawWideLine(FAB_CX, FAB_CY - 9, FAB_CX, FAB_CY + 9, 3, C_CARD);
}

// keep the selected card fully inside the scroll region
static int scrollToSel(int sel, int scroll) {
    int top = cardTop(sel);
    int bot = top + CARD_H;
    int viewH = SCREEN_HEIGHT - LIST_TOP;
    if (top - scroll < 0)            scroll = top;
    if (bot - scroll > viewH)        scroll = bot - viewH;
    if (scroll < 0) scroll = 0;
    if (scroll > maxScroll()) scroll = maxScroll();
    return scroll;
}

// which card is under a tap at screen-y (list view); -1 if none
static int cardAtY(int tapY, int scroll) {
    if (tapY < LIST_TOP) return -1;
    int base = LIST_TOP - scroll;
    for (int i = 0; i < NOTE_COUNT; i++) {
        int y = base + cardTop(i);
        if (tapY >= y && tapY <= y + CARD_H) return i;
    }
    return -1;
}

// ── DETAIL view ──────────────────────────────────────────────────────────────
#define DOC_TOP   (SB_H + 34)   // below the back bar

// measure (draw=false) or render (draw=true) the note body; returns content height
static int docBody(const Note& n, int startY, bool draw) {
    int y = startY;
    int x = 26, maxW = SCREEN_WIDTH - x - 20;

    // title + meta
    if (draw) {
        G->setFont(&s_fTitle);
        drawClipped(n.title, x, y, maxW, C_INK);
    }
    y += 24;
    if (draw) {
        G->setFont(&s_fMeta);
        G->setTextColor(C_MUTED);
        char m[40]; snprintf(m, sizeof(m), "%s . %u items", n.meta, n.bodyCount);
        G->drawString(m, x, y);
    }
    y += 18;

    for (int i = 0; i < n.bodyCount; i++) {
        const BodyLine& b = n.body[i];
        if (b.check) {
            if (draw) {
                // checkbox
                if (b.done) {
                    G->fillSmoothRoundRect(x, y, 14, 14, 4, C_ACCENT);
                    G->drawWideLine(x + 3, y + 7, x + 6, y + 10, 2, C_CARD);
                    G->drawWideLine(x + 6, y + 10, x + 11, y + 3, 2, C_CARD);
                } else {
                    G->drawRoundRect(x, y, 14, 14, 4, C_MUTED);
                }
                G->setFont(&s_fBody);
                drawClipped(b.text, x + 22, y - 1, maxW - 22, b.done ? C_META : C_INK);
            }
            y += 22;
        } else {
            // paragraph — word wrap
            G->setFont(&s_fBody);
            String line, word;
            const char* p = b.text;
            while (true) {
                char c = *p;
                if (c == ' ' || c == '\0') {
                    String trial = line.length() ? line + " " + word : word;
                    if (G->textWidth(trial.c_str()) > maxW && line.length()) {
                        if (draw) { G->setTextColor(C_INK); G->drawString(line, x, y); }
                        y += 20; line = word;
                    } else {
                        line = trial;
                    }
                    word = "";
                    if (c == '\0') break;
                } else {
                    word += c;
                }
                p++;
            }
            if (line.length()) { if (draw) { G->setTextColor(C_INK); G->drawString(line, x, y); } y += 20; }
            y += 4;
        }
    }
    return y - startY;
}

static void drawDetail(const Note& n, int scroll) {
    G->fillRect(0, SB_H, SCREEN_WIDTH, SCREEN_HEIGHT - SB_H, C_PAPER);

    // back bar
    int barY = SB_H, barH = 34;
    G->drawFastHLine(0, barY + barH - 1, SCREEN_WIDTH, C_HAIR);
    // chevron
    int cvx = 16, cvy = barY + barH / 2;
    G->drawWideLine(cvx + 5, cvy - 5, cvx, cvy, 2, C_ACCENT);
    G->drawWideLine(cvx, cvy, cvx + 5, cvy + 5, 2, C_ACCENT);
    G->setTextDatum(textdatum_t::top_left);
    G->setFont(&s_fTitle);
    G->setTextColor(C_ACCENT);
    G->drawString("Notes", cvx + 12, barY + 8);

    // decorative action icons (share + download) right side, accent — non-functional
    int iy = cvy;
    int sx = SCREEN_WIDTH - 58;                       // share: 3 dots + links
    G->fillSmoothCircle(sx,     iy - 5, 2, C_ACCENT);
    G->fillSmoothCircle(sx - 8, iy,     2, C_ACCENT);
    G->fillSmoothCircle(sx,     iy + 5, 2, C_ACCENT);
    G->drawWideLine(sx - 7, iy - 1, sx - 1, iy - 4, 1, C_ACCENT);
    G->drawWideLine(sx - 7, iy + 1, sx - 1, iy + 4, 1, C_ACCENT);
    int dx2 = SCREEN_WIDTH - 24;                      // download: arrow + base
    G->drawWideLine(dx2, iy - 6, dx2, iy + 3, 2, C_ACCENT);
    G->drawWideLine(dx2 - 4, iy - 1, dx2, iy + 3, 2, C_ACCENT);
    G->drawWideLine(dx2 + 4, iy - 1, dx2, iy + 3, 2, C_ACCENT);
    G->drawWideLine(dx2 - 5, iy + 6, dx2 + 5, iy + 6, 2, C_ACCENT);

    // doc body, clipped + scrolled
    G->setClipRect(0, DOC_TOP, SCREEN_WIDTH, SCREEN_HEIGHT - DOC_TOP);
    docBody(n, DOC_TOP - scroll + 4, true);
    G->clearClipRect();
}

static int docMaxScroll(const Note& n) {
    int h = docBody(n, 0, false) + 8;
    int viewH = SCREEN_HEIGHT - DOC_TOP;
    return h > viewH ? h - viewH : 0;
}

// tap on the back chevron/"Notes" region of the detail bar?
static bool tapBack(int x, int y) {
    return y >= SB_H && y <= SB_H + 34 && x <= 80;
}

// Compose a full frame into the canvas, then blit once (no flicker).
static void paintList(int scroll, int sel)    { drawStatusBar(); drawList(scroll, sel); flushCanvas(); }
static void paintDetail(const Note& n, int ds) { drawStatusBar(); drawDetail(n, ds);     flushCanvas(); }

// ── Entry point ──────────────────────────────────────────────────────────────
void runNotesUi() {
    // Full-screen PSRAM back-buffer (150KB). Set G before any drawing so every
    // draw lands in the sprite; fall back to the panel if allocation fails.
    s_canvas.setPsram(true);
    s_canvas.setColorDepth(16);
    s_haveCanvas = s_canvas.createSprite(SCREEN_WIDTH, SCREEN_HEIGHT);
    G = s_haveCanvas ? (lgfx::LovyanGFX*)&s_canvas : (lgfx::LovyanGFX*)&tft;

    initColors();
    loadFonts();
    // Suppress the real T-REX status bar (ClockManager/battery redraws at y<30):
    // setBlocked no-ops DisplayManager output; we draw the whole screen ourselves,
    // exactly like the lock screen does while blocked. This is what the cover does.
    displayManager.setBlocked(true);

    int view = VIEW_LIST, sel = 0, scroll = 0, cur = 0, docScroll = 0;
    static const Note kNew = {"New note", false, 0, "", "Now", nullptr, 0};

    paintList(scroll, sel);

    TouchManager& tm = TouchManager::instance();

    while (true) {
        if (LockScreenManager::getInstance().consumeJustUnlocked()) {
            displayManager.setBlocked(true);
            if (view == VIEW_LIST) paintList(scroll, sel);
            else if (cur >= 0)     paintDetail(NOTES[cur], docScroll);
            else                   paintDetail(kNew, docScroll);
        }

        // ── touch ──
        TouchEvent te = tm.poll();
        if (te.type != TouchEvent::NONE) inputHandler.updateActivity();

        if (view == VIEW_LIST) {
            if (te.type == TouchEvent::TAP) {
                int dx = te.x - FAB_CX, dy = te.y - FAB_CY;
                if (dx * dx + dy * dy <= (FAB_R + 4) * (FAB_R + 4)) {
                    cur = -1; docScroll = 0; view = VIEW_DETAIL;   // FAB → new note
                    paintDetail(kNew, 0);
                } else {
                    int hit = cardAtY(te.y, scroll);
                    if (hit >= 0) { cur = hit; docScroll = 0; view = VIEW_DETAIL; paintDetail(NOTES[cur], 0); }
                }
            } else if (te.type == TouchEvent::DRAG_MOVE) {
                scroll -= te.dy;
                if (scroll < 0) scroll = 0;
                if (scroll > maxScroll()) scroll = maxScroll();
                paintList(scroll, sel);
            }
        } else { // VIEW_DETAIL
            if (te.type == TouchEvent::TAP && tapBack(te.x, te.y)) {
                view = VIEW_LIST; paintList(scroll, sel);
            } else if (te.type == TouchEvent::DRAG_MOVE && cur >= 0) {
                docScroll -= te.dy;
                int dm = docMaxScroll(NOTES[cur]);
                if (docScroll < 0) docScroll = 0;
                if (docScroll > dm) docScroll = dm;
                paintDetail(NOTES[cur], docScroll);
            }
        }

        // ── trackball ──
        TrackballEvent tb = inputHandler.getTrackballEvent();
        if (tb != TBALL_NONE) {
            if (view == VIEW_LIST) {
                if (tb == TBALL_DOWN && sel < NOTE_COUNT - 1) { sel++; scroll = scrollToSel(sel, scroll); paintList(scroll, sel); }
                else if (tb == TBALL_UP && sel > 0)           { sel--; scroll = scrollToSel(sel, scroll); paintList(scroll, sel); }
                else if (tb == TBALL_CLICK)                   { cur = sel; docScroll = 0; view = VIEW_DETAIL; paintDetail(NOTES[cur], 0); }
            } else {
                if (tb == TBALL_CLICK)      { view = VIEW_LIST; paintList(scroll, sel); }
                else if (cur >= 0 && (tb == TBALL_DOWN || tb == TBALL_UP)) {
                    docScroll += (tb == TBALL_DOWN) ? 20 : -20;
                    int dm = docMaxScroll(NOTES[cur]);
                    if (docScroll < 0) docScroll = 0;
                    if (docScroll > dm) docScroll = dm;
                    paintDetail(NOTES[cur], docScroll);
                }
            }
        }

        // ── keyboard ──
        char k = inputHandler.getKeyboardInput();
        if (k == 'q' || k == 'Q') break;
    }

    // restore CLI
    unloadFonts();
    if (s_haveCanvas) { s_canvas.deleteSprite(); s_haveCanvas = false; }
    G = &tft;
    tft.setFont(&fonts::Font0);
    tft.setTextDatum(textdatum_t::top_left);
    displayManager.setBlocked(false);
    displayManager.clearScreen();
    displayManager.setCursor(10, outputY);
    displayManager.printCommandScreen();
}
